### ISSUE TITLE
Schema Registry: fail fast on missing configuation

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#116]
Referring to `com.snowplowanalytics.iglu.server/util/ServerConfig.scala` - if the database configuration details cannot be found, the problem will not be found until database init is done. We should fail before then.

**Comment by oguzhanunlu** [comment]
@chuwy  [Currently](https://github.com/snowplow/iglu/blob/master/2-repositories/scala-repo-server/src/main/scala/com.snowplowanalytics.iglu.server/util/ServerConfig.scala#L41-L46), assuming db information is missing, iglu registry throws `ConfigException.Missing` exception before db initialization. I observe that @alexanderdean 's comment from 2016 isn't in effect. It fails as fast as possible. I'll close this issue if prettifying exceptions isn't the point.

**Comment by chuwy** [comment]
@oguzhanunlu ok sounds reasonable. However, having pretty error messages is also desirable (but can be pushed back).

**Comment by oguzhanunlu** [comment]
Closing issue and detaching from R9. We can do prettifying later on.

**Comment by chuwy** [comment]
@oguzhanunlu please, create a ticket. Generally, all common failures should have a human-readable message. Stacktraces should be shown to user in extreme cases (and where they really make sense, e.g. for debugging).

**Comment by oguzhanunlu** [comment]
Thanks @chuwy, #351 created.
