### ISSUE TITLE
Scala Repo Server: change API root to / from /api

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#121]
Follow-on from #50 

We should move Swagger out of root, and move the API root to `/` (currently it is at `/api`). This will make an Scala repo server match the layout of a static repo.

**Comment by alexanderdean** [comment]
Agree with @chuwy - this isn't important, closing

**Comment by chuwy** [comment]
This also would be a breaking change: igluctl always assumes `/api`.
