### ISSUE TITLE
Server: preserve vendor hierarchy for access

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#122]
Having `com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0` and user with read (or write) access for `com.snowplowanalytics` our user cannot read (or write) above schema.

**Comment by chuwy** [comment]
Investigate this more closely. I cannot reproduce this bug now, probably problem was not strictly in vendor access.

**Comment by rzats** [comment]
@chuwy this was most likely fixed in #434 - at least I couldn't replicate it in 0.6.0.

**Comment by chuwy** [comment]
Closing.
