### ISSUE TITLE
Server: add consistency validation for Schema URI and actual self-describing info

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#123]
User can POST to `/schemas/com.acme` schema with "com.any.company" vendor. It means currently our URL and actual vendor are inconsistent.

One idea about it is to make self-describing info in Schema payload optional, so user can post plain JSON Schema to `/schemas/com.acme/something/jsonschema/1-0-0` and self-describing data will be inserted automatically. Or at least information in URL can have priority over information in payload.

/cc @alexanderdean what do you think about solution?

**Comment by alexanderdean** [comment]
Hey @chuwy - I like both solutions together:

* information in URL havs priority over information in payload if set
* self-describing info in Schema payload is optional, so user can post plain JSON Schema to /schemas/com.acme/something/jsonschema/1-0-0 and self-describing data will be inserted automatically

**Comment by rzats** [comment]
@chuwy this was fixed in #434 - PUT routes do check for consistency, and POST doesn't even work with URL paths  anymore.

**Comment by chuwy** [comment]
Awesome! Closing.
