### ISSUE TITLE
Schema Registry: fix apikey header setting in Swagger UI

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#125]

**Comment by alexanderdean** [comment]
@chuwy could you provide some detail on the problem here?

**Comment by chuwy** [comment]
@alexanderdean it doesn't attach `apikey` header to requests made from Swagger UI, which results in 401 statuses.

**Comment by alexanderdean** [comment]
This may be fixed by bumping Swagger. If not, let's re-evaluate to fix. But this is important.

**Comment by oguzhanunlu** [comment]
This issue is handled within #318. Closing.
