### ISSUE TITLE
Scala Repo Server: remove extra .jar extension on push

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#130]

**Comment by alexanderdean** [comment]
We need to bring this forwards - assigning to @jbeemster

**Comment by alexanderdean** [comment]
https://github.com/snowplow/iglu/blob/master/vagrant/push/publish-iglu-server.bash

**Comment by alexanderdean** [comment]
Apparently it's not benign:

    Error: Invalid or corrupt jarfile iglu-server-0.2.0.jar.jar

**Comment by jbeemster** [comment]
Found the issue @alexanderdean:

As `.jar` is appended here: https://github.com/snowplow/iglu/blob/master/vagrant/push/publish-iglu-server.bash#L138

We do not need to append here: https://github.com/snowplow/iglu/blob/master/vagrant/push/publish-iglu-server.bash#L144

or here: https://github.com/snowplow/iglu/blob/master/vagrant/push/publish-iglu-server.bash#L146

Do you want me to commit this to master or a branch?

**Comment by alexanderdean** [comment]
Thanks @jbeemster, I will fix it and try to merge back...

**Comment by jbeemster** [comment]
@alexanderdean interesting development on this one...

So the jar file outputted from sbt assembly in the `target/scala-2.10` folder works, the one that winds up in the zip file in `/dist` appears to be corrupted.  Trying to figure out what is going on there..

**Comment by jbeemster** [comment]
The only difference being this line:

`tail -c +44 ${fatjar_path} > ${fatjar_file}` which seems to corrupt our ability to run the jar locally but I presume makes it work in the ElasticBeanstalk world.

**Comment by alexanderdean** [comment]
Thanks @jbeemster , this was fixed in a rebase, closing!
