### ISSUE TITLE
Server: rename from Scala Repo Server

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#131]

**Comment by alexanderdean** [comment]
Updated name

**Comment by chuwy** [comment]
I think in ticket names this should include just `Schema Registry` without `Iglu` as `Iglu` implied by name of repository.

**Comment by alexanderdean** [comment]
Agree, thanks

**Comment by chuwy** [comment]
Hm, @oguzhanunlu how did it end-up in R9 project, but not in R9 Milestone?

But, nevertheless, @alexanderdean, I wanted to re-consider this. Do you think it is not too late (I started to think about during editing blog post) to change this to **Iglu Server**, as I believe this is most concise and informative possible project name.

* "Scala" is useless in name - this is not a library. We're all agree on that
* "Schema" also does not add much information - in the same way we can "serve" DDLs
* I think this is the only one Iglu Server that is going to exist in near feature
* "Iglu Server" is already wide-spread and acknowledged inside Snowplow name for this project, we all used to refer to it this way

So, I propose:

* Change ticket name to `Server: rename from Scala Repo Server`
* Rename all other related ticket to start with `Server:`
* Rename project directory to `2-registries/iglu-server`
* Rename all occurrences to "Iglu Server"

Huge apologies for last-moment bike-shedding.

**Comment by chuwy** [comment]
This is by the way already a name for jar-file https://github.com/snowplow/iglu/blob/master/2-repositories/scala-repo-server/project/ScalaRepoServerBuild.scala#L28

**Comment by alexanderdean** [comment]
Fine by me, the Iglu Server *provides* a RESTful schema registry; it will also provide other ancilliary services so agree it's a more appropriate name. Iglu Schema Registry is also ambiguous versus static and embedded registries...

**Comment by oguzhanunlu** [comment]
Oh, missed that one. Thanks.
