### ISSUE TITLE
Static Schema Registry: rename from Static Schema Repo

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#132]

**Comment by chuwy** [comment]
Not arguing on renaming, but just realized that we're using `repositories` key in resolver config and in too many less significant places around. May be this renaming (to Registry) would introduce too much confusion?

**Comment by alexanderdean** [comment]
I hear you but registry is a better name... I think if we make the change now it's not too late. We can have a few legacy references to repository for a little while...

**Comment by chuwy** [comment]
Fair enough.
