### ISSUE TITLE
Scala Core: add

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#135]
Here's a proposal for scala-common library:

* Contains common data types using in all our applications and libraries working with Iglu, such as `SchemaVer`, `SchemaCriterion`, `SelfDescribingSchema` etc.
* Most common methods to work with these data types, such as `parse`, `validate`, `compare`, `generateIgluUri` etc.
* Some pieces (like regular expressions) can serve as reference implementation for Iglu on other platforms (JS, ObjC)
* Zero-dependency. It should be really small and slick and updated only when we're introducing some changes in related concepts (like "let's forbid underscores in Schema names"), not when new binary-incompatible scalaz is out. I think we can even omit a json4s dependency, all requiring implementation details, like parsing self-describing info can be injected via type classes or implicit classes.

We can roll it out in the near future, then use it in schema-guru, schema-ddl, iglu-scala-server, iglu static generator and only after that start to use it in iglu-scala-client. All these (and probably more) projects now have implemented various chunks of this functionality separately.

/cc @alexanderdean

**Comment by alexanderdean** [comment]
Hi @chuwy - this sounds great to me! Hooking in @fblundun, @ninjabear for feedback...

**Comment by fblundun** [comment]
@chuwy - I think this is a good idea. We should probably be doing something similar for e.g. common enrich. Lots of apps need to access the EnrichedEvent and BadRow classes but most of them don't need the actual event enrichment logic.

Feedback: I think we should call it something like `iglu-core` or `schema-common` to distinguish it from other Scala libraries we release in the future.

**Comment by alexanderdean** [comment]
I like iglu-core! I think:

* The folder should be 0-common/scala-core (because it's obviously a part of Iglu)
* The artifact should be iglu-core (because it's obviously a JVM artifact and we are unlikely to release a separate Java one)

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by alexanderdean** [comment]
Note the change in ticket name
