### ISSUE TITLE
Registry Syncer: add counter and auto-generation of keys

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#140]
(Title of this ticket is WIP)

Snowplow Mini has a really nice repo uploading Bash script. Would be nice to port this into Iglu proper.

**Comment by chuwy** [comment]
Changed the title. Also I think we'll need to rewrite it in python someday. As we anyway dependent on python, sed, awk, curl and yet need not very elegant solutions to output pretty error messages.

**Comment by alexanderdean** [comment]
This will move into the Iglu CLI, which needs to be in Scala (given all the IP we have around the static generator): https://github.com/snowplow/iglu/issues/144
