### ISSUE TITLE
Iglu CLI: lint Redshift DDL?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#146]
Ported from https://github.com/snowplow/schema-guru/issues/86

**Comment by chuwy** [comment]
> Not sure how we would do this:

> 1. Use a live Redshift database?
> 2. Strip Redshift-specific DDL and use a local Postgres?
> 3. ...?

I'd go with live Redshift database. It doesn't make a lot of sense to check correctness of DDL at the same time removing most fragile part of this DDL.
