### ISSUE TITLE
Scala Core: add support for Unversioned Schema

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#147]
```
com.acme/order/jsonschema/?-?-?

com.acme/order/jsonschema/1-?-?

com.acme/order/jsonschema/1-3-?
```

**Comment by alexanderdean** [comment]
Need a good name for this...

**Comment by chuwy** [comment]
* Schema placeholder
* Schema matcher
* Schema basis

**Comment by chuwy** [comment]
Just random thoughts on it.

I think would be a very common to advice users to set it as `1-?-?`, because for me if data-producers are changing Schema of data so it become back-and-forward incompatible - they usually announce it publicly and change API path (`/api/v2`) or similar.

**Comment by alexanderdean** [comment]
I hear you - but I'm not sure I trust data-producers to understand precisely what changes are backwards compatible... Think how many APIs are generated by dynamically typed languages as a starting point!

**Comment by alexanderdean** [comment]
What about `PartialVersion` instead of `UnversionedSchema`?

**Comment by chuwy** [comment]
I like `PartialVersion` more (functions, right), but problem is that `?-?-?` not even partial, it is really unversioned.

**Comment by chuwy** [comment]
`OpenVersion`?

**Comment by alexanderdean** [comment]
I really like `OpenVersion`. It says that we are staying open-minded about what schema version validates this schema...

**Comment by chuwy** [comment]
So, let it be.
```scala
sealed trait SchemaVer
case class OpenVersion() extends SchemaVer
case class FinalVersion() extends SchemaVer
```
What about final?

**Comment by alexanderdean** [comment]
`ClosedVersion` - meaning fully defined?

**Comment by chuwy** [comment]
Yes. May be if we're going to consider `ClosedVersion`... what about `SealedVersion`?

**Comment by chuwy** [comment]
Thinking about adjective. "Open-versioned data" sounds really good. Close-versioned... not so good.

**Comment by alexanderdean** [comment]
* FullVersion
* ExplicitVersion
* ...

**Comment by chuwy** [comment]
Pushing back as not related to r5 main scope (igluctl).

**Comment by alexanderdean** [comment]
Where did we end up on the naming of these?

**Comment by chuwy** [comment]
Good question. Let's go with `PartialVersion` and `FullVersion` maybe, if you don't have strong opinion against it?

**Comment by alexanderdean** [comment]
Okay, sounds good

**Comment by chuwy** [comment]
Bringing this into R7 as it seems we have enough time and it's already partly implemented.
