### ISSUE TITLE
Scala Core: placeholder for support for schema migrations

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#149]
So instead of users creating 1-0-0, 1-0-1, 1-0-2, they create 1-0-0 and then just deltas, something like:

``` json
{ "operation": "ADD", "name": "userId", "type": "string" }
```

Kind of thing. We should try and keep this as close to the JSON Schema and Avro standards as possible. Potential scope for contributing these to the parent standards?

**Comment by chuwy** [comment]
I explored this field and seems only relative standard is [JSON Patch](http://jsonpatch.com/). 
It is an RFC draft (for quite long time), but it is related to instances, thus very permissive. We need a standard which doesn't allow us to create invalid JSON Schemas.

**Comment by chuwy** [comment]
We can add requirements here and start to sketch a JSON Schema somewhere. @alexanderdean what operations do you think we need? `ADD`, `DROP`, `ALTER`? What about `RENAME`?
`{ "operation": "ADD", "name": "$.userId", "type": "string" }`. I think its wise to use JSONPath, not a  standard either, but has a broadest adoption among similar tools.

**Comment by alexanderdean** [comment]
Hey @chuwy - agreed, let's start speccing this out here. I'd start by looking at the various `ALTER` options in SQL and seeing what we want to keep/tweak/add...

**Comment by chuwy** [comment]
I also think it is good idea to use inner object with subschema instead of adding Schema properties as first-level properties, so instead of:
```json
{ 
  "operation": "ADD",
  "name": "userId",

  "type": "string",
  "maxLength": 32
}
````
 it would be
```json
{
  "operation": "ADD",
  "name": "userId",

  "schema": {
    "type": "string",
    "maxLength": 32
  }
}
```
So, we're reusing entities: `schema` property is valid subschema and whole Schema Migration easier to scheme.
Need a better name for `schema`. `properties` bad idea either.

**Comment by alexanderdean** [comment]
A migration could be a JSON array (so ordered) of the above statements?

A couple of process points:

* We should obviously define JSON Schemas for the whole migration format
* We should test the migration format with all existing schemas in Iglu Central that have undergone migration

**Comment by chuwy** [comment]
We cannot have idempotent ALTERs. They *must* contain only new properties. Otherwise it will be impossible to determine correct smallest possible SchemaVer bump.

**Comment by alexanderdean** [comment]
> We cannot have idempotent ALTERs. They must contain only new properties.

What does this mean precisely @chuwy ?

**Comment by chuwy** [comment]
I had two possible ways to define migrations previously. First one was "idempotent". For example, consider following migration:
```json
{
  "operation": "ALTER",
  "name": "$.userId",

  "schema": {
    "type": "string",
    "default": "none`"
  }
}
```
it just sets `type` to `string` and `default` to `none`. It doesn't care if for e.g. `default` already was `none` or `type` was already `string`. But I just realized that looking **only** to this migration we cannot determine if this is an ADDITION (set `default`) or REVISION (set `type`). On the other hand, if we restrict ALTERS to have only fields that changed this should look like:
```json
{
  "operation": "ALTER",
  "name": "$.userId",

  "schema": {
    "default": "none`"
  }
}
```
And we can easily determine this is an ADDITION which just sets `default`.

**Comment by alexanderdean** [comment]
That makes total sense @chuwy - I like the way this is evolving!

**Comment by chuwy** [comment]
Just FYI. Seems authors of JSON Schema started to think about Draft v5 and they considering support of JSON Pointer. For example they have [proposed](https://github.com/json-schema/json-schema/wiki/v5-Proposals#semantic-format-related-optional) `json-pointer` as a string format (which is fantasic!) and also propose JSON Pointer for various internal things.

Taking above in account I think we can consider it as an alternative to JSONPath as well.

JSON Pointer is an alternative to JSONPath standard (basically, JSONPath isn't a standard in any sense). It is an IETF [Draft](https://tools.ietf.org/html/rfc6901) and comparing to JSONPath looks simpler. But also [less expressive](http://susanpotter.net/blogs/software/2011/07/why-json-pointer-falls-short/) and I couldn't find any Scala implementations.

**Comment by alexanderdean** [comment]
Great spot!

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-scala-core/issues/27
