### ISSUE TITLE
Scala Core: consider adding of Resolver config

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#154]
Currently, format of Resolver configuration is described only in Scala Iglu Client, but nothing in it is specific for Scala, also Resolver configuration looks like core concept for Iglu and therefore should be parseable from any other language.

``` scala
case class RepositoryRefConfig(name: String, instancePriority: Int, vendorPrefixes: List[String])

trait RepostiroryRef { val config: RepositoryRefConfig }
case class HttpRepositoryRef(config: RepositoryRefConfig, uri: String, apikey: Option[String]) extends RepositoryRef
case class EmbeddedRepositoryRef(config: RepositoryRefConfig, path: String) extends RepositoryRef

case class Resolver(cacheSize: Int, repos: List[RepositoryRef])
```

On the other hand, I see no clear benefits for having Resolver configuration anywhere except client (basically `client == resolver`). I think it should be added in Core whenever any other application require `resolver_config.json` parsing.

**Comment by chuwy** [comment]
One hazy benefit is excluding [embedded schemas](https://github.com/snowplow/iglu-scala-client/tree/master/src/main/resources/iglu-client-embedded/schemas) from Iglu Client.

**Comment by alexanderdean** [comment]
I think this is a good idea @chuwy !

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-scala-core/issues/25
