### ISSUE TITLE
Add wiki page explaining Iglu registry resolution algorithm

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#155]
This is important for Iglu client implementors.

**Comment by chuwy** [comment]
I'm descheduling it from milestone, since it doesn't affect codebase, I'll publish wiki page today.

**Comment by alexanderdean** [comment]
Great, thanks

**Comment by chuwy** [comment]
This is done https://github.com/snowplow/iglu/wiki/Schema-resolution. Closing.
May be @ihortom may want to add something or make language more technical and explicit.
