### ISSUE TITLE
Schema DDL: Move schema-ddl into iglu

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#158]
Since `ddl` command is now moving out from Schema Guru and arriving into Iglu CLI, schema-ddl losing its initial purpose as stand-alone lib. 
Now schema-ddl basically has a single unique functionality - Redshift DDL AST, which can also be a part of Iglu.

**Comment by alexanderdean** [comment]
Let's do this one relatively soon. This should be a library that is available for other libraries to use.

**Comment by chuwy** [comment]
Hey @alexanderdean!

Just an update on this. Yesterday I started to move schema-ddl into Iglu and realized one very interesting thing.

On a very beginning of Schema Guru, internally our Schema was just a plain `JValue`, which was very inconvenient, unsafe and error-prone. Near 0.3.0 release I refactored it into set of AST-like classes built around JSON Schema types (`StringSchema`, `NumberSchema`, `ArraySchema`, etc). This allowed us to transform Schemas more safely and gave some guarantees, but still has significant disadvantages. Particularly, this representation makes sense only for deriving Schemas and nowhere else. When we embedded schema-ddl into SG, we didn't even used this AST and just worked with JSON Schemas again as plain `JValue`s. Not to say, we couldn't construct a value from Schema with missing type (missing type is absolutely valid in JSON Schema, but we always have it inside SG, so I didn't care about it).

When I started to describe DDL AST, with only single Redshift DDL, I realized that we could provide perfectly valid, reusable AST for JSON Schema, which is Data Definition Language in some sense as well. 

In the meantime I was thinking a lot about this meaningful reusable AST for Schema Guru and I think I have really good implementation. And I guess this would be a mistake to leave it inside Schema Guru as JSON Schema AST in Iglu has same value as Redshift AST.

So, what I propose is to make another package `com.snowplowanalytics.iglu.ddlast.jsonschema` along with  `com.snowplowanalytics.iglu.ddlast.redshift`. It will have almost same very generic and dependency free spirit as iglu-core and DDL AST still will be included in Schema Guru, but with different purposes. 

This gives us huge benefits:
+ More type-safety (needless to say)
+ We will need to parse (and pass around) JSON Schemas into meaningful representation in many apps
+ This can be useful not only for Snowplow-related purposes
+ It will be useful in a distant future if we decide for example build some Iglu Web UI with Scala.js

**Comment by chuwy** [comment]
ETA:
+ We can build useful for our purposes AST very quickly. It will include all properties we're using in Schema Guru and in igluctl (skipping props like `exclusiveMaximum`, `uniqueItems` etc). I guess I will finish it today.
+ Longest part is the integration into Schema Guru. But taking in account some scheduled features for SG I guess little refactoring will be in its favor. May be 1-2 days only to swap current AST with proposed one.
+ Half-day to complete this AST in accordance with JSON Schema v4. This probably can be scheduled for future.
+ Factor-out json4s. This can be scheduled for a very distant future.

**Comment by alexanderdean** [comment]
This sounds awesome @chuwy - please proceed exactly as you propose above!

**Comment by chuwy** [comment]
Hey @alexanderdean.

I think as we decided to leave project name `schema-ddl` so far, perhaps we need to rename this ticket it to something like "Move schema-ddl into iglu" and change packages from `com.snowplowanalytics.schemaddl` to `com.snowplowanalytics.iglu.schemaddl`?

`schemaddl` also now includes new package `jsonschema` with lot of new functionality (used by igluctl). Should this be reflected in separate ticket?

**Comment by alexanderdean** [comment]
Sounds good to me. Yep separate ticket for jsonschema support
