### ISSUE TITLE
Common: Add Sonatype credentials to .travis.yml

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#159]
Required for publishing to Maven Central

**Comment by alexanderdean** [comment]
@chuwy could you add the actual credential names to this ticket's description, so we have them somewhere?

**Comment by chuwy** [comment]
Like that? ^^

**Comment by alexanderdean** [comment]
Are those the right cred names? They don't look like Sonatype creds, they look like Bintray creds

**Comment by chuwy** [comment]
Sorry. Morning silliness. Fixed. I'm not sure however these are right, because I not use them explicitly, but `sbt-bintray` is aware of these, so I guess names should be correct.

**Comment by alexanderdean** [comment]
Great thanks @chuwy !
