### ISSUE TITLE
Server: add support for ∧ (min) and ∨ (max)

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#162]
Given the schemas for [`com.amazon.aws.cloudfront/wd_access_log`](https://github.com/snowplow/iglu-central/tree/master/schemas/com.amazon.aws.cloudfront/wd_access_log/jsonschema), if I request:

```
// Request                                                  // Response
com.amazon.aws.cloudfront/wd_access_log/jsonschema/1-∨-∨ -> com.amazon.aws.cloudfront/wd_access_log/jsonschema/1-0-4
com.amazon.aws.cloudfront/wd_access_log/jsonschema/∧-∧-∧ -> com.amazon.aws.cloudfront/wd_access_log/jsonschema/1-0-0
com.amazon.aws.cloudfront/wd_access_log/jsonschema/2-∧-∧ -> null
```

This should replace any existing "/latest" functionality.

This is a core building block for schema inference.

**Comment by chuwy** [comment]
Pushing back as not related to r5 main scope (igluctl).

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-server/issues/22
