### ISSUE TITLE
igluctl: decide how to support ∧ (min) and ∨ (max) for static repos

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#163]
We can't expect users to maintain these manually. Does this mean that there is _always_ some kind of pre-processing step even with a static repo?

**Comment by chuwy** [comment]
Pushing back as not related to r5 main scope (igluctl).

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/48
