### ISSUE TITLE
igluctl: add linting for nonsense schemas 

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#164]
Although JSON Schema can validate some part of itself and Schemas like `{"minLength": -1}` are invalid it is still very happy about nonsensical schemas (instances of which cannot be instantiated), like `{"minimum": 1, "maximum": 0}`. 

Here I'm trying to list these cases.

* properties are inconsistent with types: Example `{"type": "object", "maxLength": 1}`
* `minimum` is higher than `maximum`
* `minLength` is higher than `maxLength`
* `minItems` is higher than `maxItems`
* `minProperties` is higher than `maxProperties`

**Comment by chuwy** [comment]
Bringing it forwards, as I implemented it anyway.

**Comment by alexanderdean** [comment]
Tweaked title
