### ISSUE TITLE
Scala Core: fix handling of $schema on body extraction

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#165]
When we extracting `SelfDescribingSchema` from valid Self-describing JSON Schema, it can leave incorrect `$schema` key pointing to `http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#`, which is incorrect because plain body of Self-describing Schema doesn't conform it.

Isn't critical, but I'm scheduling it for Scinde Dawk, since we're going to make a release of Iglu Core anyway.

**Comment by chuwy** [comment]
Pushing back as not related to r5 main scope (igluctl).

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-scala-core/issues/24
