### ISSUE TITLE
Scala Core: split SchemaKey into data- and schema-specific

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#167]
Until now we had a case class SchemaKey with vendor, name, format and version, where version was always **explicit** (using new terminology), because its model, revision and version always were known.

This `SchemaKey` was essentially bi-directional. We could describe data instance with it, having `{"schema": "iglu:com...", "data": {}}` and also we could describe schema with it `{"self": {"vendor": "com.acme"}}`.

But since we're introducing new `OpenVersion` concept, it cannot be true anymore. Because we cannot have self-describing Schema with open (unknown) version. Do we?

So, my current vision looks like following:

``` scala
// Describing data
case class SchemaKey(
  vendor: String,
  name: String,
  format: String,
  version: SchemaVer            // both open and explicit
)

// Describing Schemas
case class SchemaInfo(
  vendor: String,
  name: String,
  format: String,
  version: ExplicitVersion      // always known
)
```

At first glance it looks like something that was cool in theory just broken by practiacal needs, but actually I never liked idea to use same entity for describing both parts. They looks different (record vs string) and feel different.

**Comment by alexanderdean** [comment]
LGTM!

**Comment by chuwy** [comment]
Done as part of https://github.com/snowplow/iglu/issues/147
