### ISSUE TITLE
igluctl: add iglu lint severity levels

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#175]
I'd like us to hold Iglu Central schemas to a very high standard - to prevent issues like e.g. https://github.com/snowplow/iglu-central/issues/382

My suggestion is to have `igluctl lint` severity levels, where each level is "tougher" about the schema definition. Some notes:

* We would add a detailed table to the documentation describing what is enforced at each severity level
* We would slowly increase the severity level for Iglu Central linting, fixing existing schemas as we go to avoid breaking the build

Fleshing out this ticket, `igluctl lint` currently uses an implicit/default severity level of 1. In this ticket we would add `--severity 2`, where this new severity:

* Rejects numbers without min and max because they don't provide enough steer on smallint / int / bigint
* Rejects strings without a maxLength because they don't provide enough steer on what e.g. a Redshift varchar length should be

**Comment by chuwy** [comment]
Ideas for further severity levels (or add to 2nd?):

* array without `maxItems`
* object with `additionalProperties: true` and without `maxProperties`

**Comment by alexanderdean** [comment]
Hey @chuwy - interesting ideas - can we move them into a new ticket as a discussion ground. I think we have enough for Iglu 6 already.

**Comment by chuwy** [comment]
Done https://github.com/snowplow/iglu/issues/216
