### ISSUE TITLE
Schema DDL: make it possible to specify schema name

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/iglu#196]
A boring one but would save a lot of time.

Currently all the ddl assumes that the schema name is `atomic`. 

Often it is not.

It would be nice to specify this somehow - either on the command line or maybe better via a config file. (Note that for an individual user this is not likely to change, so a command line arguement might be a bit tiresome.)

**Comment by chuwy** [comment]
It is possible! `igluctl --schema notatomic ...`.
Although I always wanted to rename it to `dbschema`.

**Comment by alexanderdean** [comment]
Rename sounds good...

**Comment by yalisassoon** [comment]
Great! Where's that documented?

**Comment by alexanderdean** [comment]
https://github.com/snowplow/iglu/wiki/Igluctl#43-other-options

**Comment by chuwy** [comment]
@yalisassoon can we close this ticket?

**Comment by yalisassoon** [comment]
Yes - closing
