### ISSUE TITLE
igluctl: add ability to provide full URL as registry root

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#199]
Currently `host` argument in `static push` should be just `host:port` pair without `http://` prefix. We should allow `http://` prefix and `https://` with default to `http://`.

**Comment by chuwy** [comment]
Changed title a bit. I think as it is absolutely valid to have registry root not in server root (for example `http://example.com/analytics/iglu/schemas/` is valid URL for [Scala Client](https://github.com/snowplow/iglu/wiki/Iglu-client-configuration)) we need ability to provide such URLs.

**Comment by alexanderdean** [comment]
SGTM
