### ISSUE TITLE
igluctl: add static s3cp subcommand

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#201]
At the moment we use `aws s3` to push from a local repo to S3 [1]:

```bash
aws s3 cp schemas s3://snowplow-com-mycompany-iglu-schemas/schemas --include "*" --recursive
```

[1] https://github.com/snowplow/iglu-example-schema-registry#22-upload-the-schemas-to-iglu-for-the-full-pipeline

Let's explore fuller management of a static repo on S3 from igluctl, e.g. wrapping the above functionality...

**Comment by alexanderdean** [comment]
Brought forward; this was the other feature for igluctl we discussed on the call today - it would mean we can stop referring to `aws s3` in our READMEs...

**Comment by yalisassoon** [comment]
If a user can add their AWS creds in a one-off way, that is really nice.
If a user can configure their S3 location for schemas and jsonpaths in a one-off way, that is really nice too - because then you simply run a 'sync' command or a 'push' command to repush all the schemas and jsonpaths.

**Comment by alexanderdean** [comment]
From Boto (and I bet Java SDK is the same), if a user has already run say `aws configure --profile eng-sandbox` locally, then that profile is available to any Boto code...

**Comment by yalisassoon** [comment]
So our primary goal is to move AWS CLI from the schema'ing process.

That means we have to push both schemas and jsonpath files to s3 for this to work.

I'm relaxed about whether that is one or two separate commands. I'm relaxed about whether the command for publishing schemas looks like the one for publishing schemas to the static server repo.

Over time, we need to move to having a config file where the user defines a number of 'endpoints' e.g. 'testing' (which will most likely be snowplow-mini) and production (which will be their full snowplow pipeline) and then can issue simple commands like:

```
iglu push test
```

or 

```
iglu push production
```

In the meantime though I just want a set of unambiguous commands that we can paste in the [schema registry readme](https://github.com/snowplow/iglu-example-schema-registry/blob/master/README.md).

**Comment by alexanderdean** [comment]
Sounds like a plan!

**Comment by yalisassoon** [comment]
This doesn't seem to be working:

```
$ aws s3 mb s3://snowplow-com-test-iglu-schemas
make_bucket: s3://snowplow-com-test-iglu-schemas/
$ aws s3 mb s3://snowplow-com-test-iglu-jsonpaths
make_bucket: s3://snowplow-com-test-iglu-jsonpaths/
$ ls
README.md jsonpaths schemas   sql
$ ../igluctl static s3cp schemas s3://snowplow-com-test-iglu-schemas
FAILURE: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: D39C06F3849C32B6), S3 Extended Request ID: 4G2ugb9RjMTydW7EqP92ee9L4bv/gHGUrEP7GMZgU3lQ9cLDhGZNH7B5SJmcIFA7hebXLampaQs=
FAILURE: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: F0EE8FF8E1D1494A), S3 Extended Request ID: 0XqH3fSaXqSAj7XWQeESOdDt6NDyHpqHL6I975Gt1+raPtUseK1QiEsAI6pcq1ZWtsOr1PCojto=
FAILURE: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 048BCB6A0BCFFD71), S3 Extended Request ID: tkFJX4uQ/Fpjkk/cihmQWfwnBrXlzACbTgtwv9nAuNAcMaZ+3Efga8NaG4aP26op2PRanvtcZ6Y=
TOTAL: 0 files were successfully uploaded
TOTAL: 3 errors were encountered
$ ../igluctl static s3cp schemas snowplow-com-test-iglu-schemas
FAILURE: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 06A514F3DFB38C18), S3 Extended Request ID: Y/OO8n90DgB/jP5IOtm04hUwTqfTrETK3aclNoP4xwPd22LXyop+kyU5TqMfPaC5p+Qa/OfTofc=
FAILURE: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: A9C233A2D3200DE8), S3 Extended Request ID: EdQUBnJ8QvLbzTTlCHA0HyoN+05Q7vWCZtqjWa2drN1yEnpU2F1E0LQcsQGVQ7V4xIWIbpLCWfc=
FAILURE: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 3463370A6E81E713), S3 Extended Request ID: nADFkfjzhfP75aupQSWU7r+oUYWyNVzhw4IKL0P+R8+i7oQ2IO6P5PZEwi6XU4XwGCVINKyo5ms=
TOTAL: 0 files were successfully uploaded
TOTAL: 3 errors were encountered
```

The buckets in question are in the `eu-west-1` region.

**Comment by yalisassoon** [comment]
@chewy - can you please provide me with instructions on how to enter the AWS credentials? Remember that the expectation is that a user who uses `igluctl` will *not* have setup the AWS CLI: so it's essential that we have a documented process for adding the creds. This will also enable me to make sure I'm testing it in the way our users will do.

The documentation should also include an example e.g. it's very unobvious to me whether or not to include an `s3 prefix` on the bucket name for example.

**Comment by chuwy** [comment]
Hi @yalisassoon.

Basic way to provide credentials is to specify them via [CLI options](https://github.com/snowplow/iglu-example-schema-registry/pull/4/files#diff-04c6e90faac2675aa89e2176d2eec7d8R85). This doesn't require to install AWS CLI.

So, basically, we have following chain:

1. First - it will try to get credentials from `accessKeyId` and `secretAccessKey` options.
2. If above aren't provided - it will try to get profile name from `profile` option
3. If above isn't provided - it will try to get `accessKeyId` and `secretAccessKey` from environment variables (this is of course not recommended way, but this is how AWS SDK works)
4. If above aren't found it will try to get profile named `default` from `~/.aws/credentials`.

**Comment by chuwy** [comment]
Above doesn't take in account region. It should be explicitly provided as `region` option in first case or can be placed in configuration files (or environment variable) as well. AWS SDK's default region is us-west-2 - they state this is default region they recommend for new users.
