### ISSUE TITLE
igluctl: add option to upload schemas publicly

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#202]
Currently it uploads has hardcoded `isPublic=false`. We need to add option `--public`.

**Comment by alexanderdean** [comment]
Why would it default to public?

**Comment by chuwy** [comment]
I think it would be more consistent with static registry. If one already has static registry which works without apikeys - he probably wants to just make this to work in scala registry as it was. Whenever one decides to make some schemas private - he can do it explicitly.

**Comment by alexanderdean** [comment]
But public-by-intention schemas are extremely rare. We have them in Iglu Central, and there may in the future be software companies with public registries for their APIs etc, but I know of none currently.

I don't imagine a new user of Iglu Scala Schema Registry would expect their company's schemas to be public - especially as private schemas is one of the few features that the Scala registry has over the static registry. Even with Snowplow Mini, with the proper auth in Snowplow's `iglu_resolver.json` there is no need for schemas to be public.

**Comment by chuwy** [comment]
Ok. That makes sense. Let's leave private by-default.
