### ISSUE TITLE
Placeholder for documentation updates

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#203]
* Igluctl wiki page
* A PR into iglu-example-schema-registry with corresponding updates

Not for changelog, close and de-schedule when done.

**Comment by yalisassoon** [comment]
Make it easier to find / surface the wiki page (e.g. from the [source code readme](https://github.com/snowplow/iglu/tree/master/0-common/igluctl)).

PR into https://github.com/snowplow/iglu-example-schema-registry/blob/master/README.md

**Comment by chuwy** [comment]
Igluctl wiki page is written, PR is published. Closing this.
