### ISSUE TITLE
Server: fix incorrect $schema in original self-desc

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#211]
It is `http://json-schema.org/draft-04/schema#` while should be `http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#`.

**Comment by alexanderdean** [comment]
Is this to match: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#L2

**Comment by chuwy** [comment]
Right. Sorry.

**Comment by alexanderdean** [comment]
I didn't follow the rationale for closing?

**Comment by chuwy** [comment]
Agh. Didn't check a link, for a second thought this is supposed `$schema`.

**Comment by rzats** [comment]
@chuwy this is fixed in #434 - https://github.com/snowplow/iglu/blob/release/0.6.0/2-repositories/iglu-server/src/main/scala/com/snowplowanalytics/iglu/server/model/Schema.scala#L53

**Comment by chuwy** [comment]
Cool. Closing.
