### ISSUE TITLE
igluctl: consider adding ability to not override assets

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#212]
Now we're using HTTP PUT, which silently overrides all published schemas. May be there's a use case for disabling this overriding by using POST. Not for R6.

As @yalisassoon noted - if we're going to implement this - it should be consistent with how copying to S3 works.

**Comment by alexanderdean** [comment]
Hmm yes - it sounds like a bit of a footgun. Are you thinking of a `--no-override` or `--safe` arg?

**Comment by alexanderdean** [comment]
Off topic - but do we have a dry-run flag yet for igluctl? It's invaluable with Factotum, SQL Runner etc...

**Comment by chuwy** [comment]
Yes, we were thinking about `--no-override` flag. 
We don't have dry-run flag, but we have force flag for `static generate`.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/46
