### ISSUE TITLE
Schema DDL: refactor JsonSchema-to-Redsfhit transformation using new schema flattener

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#213]
As previous (R5) part of Schema DDL refactoring I added new [flattener](https://github.com/snowplow/iglu/blob/master/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/FlatSchemaNext.scala) algorithm along with legacy [stringly-typed one](https://github.com/snowplow/iglu/blob/master/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/FlatSchema.scala). Former isn't enabled yet, but we need to switch to it and remove latter one.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/34
