### ISSUE TITLE
igluctl: placeholder for further severity levels

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#216]
- array without `maxItems`
- object with `additionalProperties: true` and without `maxProperties`

**Comment by chuwy** [comment]
Having strict enough Schema - we can derive VARCHAR length for complex objects extremely precisely: https://github.com/snowplow/iglu/issues/187

**Comment by chuwy** [comment]
Also, I think severity of top-level properties isn't always very important, however it can be extremely important for mentioned above complex objects, because without a clues about minimums/maximums it can have huge dispersion in VARCHAR size.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/44
