### ISSUE TITLE
igluctl: warn user if he tries to generate DDL not for 1-0-0

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#221]
Problem: if user creates ADDITION schema (1-0-1 with new fields) and then generates DDL with `igluctl static generate jsonschema/com.acme/event/jsonschema/1-0-1` Igluctl will output DDL where new columns will be added in the middle of table, whereas new ADDITIONS should always be in the end of table. Instead, if user adds new fields - he always need to generate DDLs with `igluctl static generate jsonschema/com.acme/event/jsonschema` (no exact file).

This also leads us to the fact that igluctl should treat Iglu registry as single entity and usually should not process each schema individually.

**Comment by alexanderdean** [comment]
> This also leads us to the fact that igluctl should treat Iglu registry as single entity and usually should not process each schema individually.

Agreed. I'd actually say the current behavior is a bug - `igluctl static generate jsonschema/com.acme/event/jsonschema/1-0-1` should restrict the **output** of the command, but it should not incorrectly restrict the **inputs** into the generation of 1-0-1 DDL.

**Comment by chuwy** [comment]
> This also leads us to the fact that igluctl should treat Iglu registry as single entity and usually should not process each schema individually.

Just an addition to whole-registry/per-file problem: if we have previous versions of JSONPaths/DDLs generated not with `igluctl`/`schema-guru` - new version will not take in account order of those manually generated fields. If user is not attentive enough his load will be broken.

/cc @jbeemster

**Comment by oguzhanunlu** [comment]
Per @chuwy 's suggestion, let's proceed here as following;

* If user specified folder and one of schemas has no 1-0-0 or misses any other schemas in between (like it has 1-0-0 and 1-0-2) - refuse to do anything (but proceed with --force option)
* If user specified full path to file with schema and this file is not 1-0-0 - just print a warning
* If user specified full path to file with schema and it is 1-0-0 - all good
