### ISSUE TITLE
igluctl: Adding default owner to generated DDL

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#222]
Hi @chuwy, what are your thoughts on potentially adding `ALTER TABLE schema.table OWNER TO storageloader` either by default or as a flag such that this statement is appended to the Redshift DDL statements?

**Comment by chuwy** [comment]
Hey @miike. That's an interesting question. 

I think if we grant ownership of whole DB schema to `storageloader` as [proposed in docs](https://github.com/snowplow/snowplow/wiki/setting-up-redshift#51-creating-a-user-for-the-storageloader) - per-table ownership would be overkill? Could you provide more rationale behind it?

One more important thing is that SQL table definitions (as well as JSON Schemas) assumed to be pure data description, whereas `ALTER TABLE schema.table OWNER TO storageloader` looks more like accidental complexity and too snowplow-specific.

**Comment by miike** [comment]
I can see that we grant usage (and ownership) of the atomic and atomic.events table respectively there, do we actually grant ownership of the schema though? The alternative may be to use `ALTER DEFAULT PRIVILEGES` such that any new tables created under atomic have the appropriate permissions. I agree around the Snowplow specificity note.

**Comment by poberherr** [comment]
Yes ok good point. 
I missed that and wrote a script to set the permissions in each table.
