### ISSUE TITLE
igluctl: use UTC in header generation of Redshift DDL files

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#223]
@chuwy What are your thoughts on adding generated time for Redshift header DDL statements as UTC, or alternatively adding the UTC offset if the datetime is in local time?

https://github.com/snowplow/iglu/blob/master/0-common/igluctl/src/main/scala/com.snowplowanalytics.iglu/ctl/GenerateCommand.scala#L146

**Comment by chuwy** [comment]
That's make sense @miike!
