### ISSUE TITLE
Schema DDL: add check that root of JSON Schema has type object

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#224]
Currently we cannot generate any meaningful DDL for JSON Schemas with array as root level and `igluctl static generate` gives following error: ` 'flattenJsonSchema' - JsonSchema does not begin with an 'object' & 'properties' in [com.acme/event/jsonschema/1-0-0] Schema`. 

But `lint` doesn't give any warning about it.

**Comment by alexanderdean** [comment]
See also https://github.com/snowplow/snowplow/issues/2451

**Comment by oguzhanunlu** [comment]
@chuwy I tested a json schema with type `array`. Although `static generate` produced same error,  `lint` did give errors. Since last update on this issue was 1 year ago, I could make use of an update here.

**Comment by chuwy** [comment]
What was the lint error, @oguzhanunlu?

```
iglu-central > igluctl lint schemas/com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-1
SUCCESS: Schema [/Users/chuwy/workspace/iglu-central/schemas/com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-1] is successfully validated
TOTAL: 1 Schemas were successfully validated
TOTAL: 0 invalid Schemas were encountered
TOTAL: 0 errors were encountered
```
