### ISSUE TITLE
igluctl: table ownership setup as part of DDL

### ISSUE THREAD

**Issue by ihortom** [snowplow/iglu#225]
MSP suggested adding table ownership setup to be included into DDL of the table. It makes sense as many users simply forget to amend the ownership once the table is created.

I guess this could be achieved with an additional option passed to the command. Something like this:

```sh
$ ./igluctl static generate --set-owner {{owner}}
```

The command would generate the DDL to `CREATE` the table followed by `ALTER`.

**Comment by chuwy** [comment]
https://github.com/snowplow/iglu/issues/222
