### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by estezz** [snowplow/iglu#229]
I cloned the project on my mac book, but it does not build.

```
10:16:12-uwoesle~/workspace/iglu/2-repositories/scala-repo-server(master)$ sbt assembly
[info] Loading project definition from /Users/uwoesle/workspace/iglu/2-repositories/scala-repo-server/project
[info] Set current project to iglu-server (in build file:/Users/uwoesle/workspace/iglu/2-repositories/scala-repo-server/)
[info] Compiling 19 Scala sources to /Users/uwoesle/workspace/iglu/2-repositories/scala-repo-server/target/scala-2.10/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.1. Compiling...
error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
error: error while loading Comparator, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/util/Comparator.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 20)
error: error while loading AnnotatedElement, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 76)
error: error while loading Arrays, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/util/Arrays.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 765)
/var/folders/pk/3rj1jqvj5dlgml9p6q4nx5zrt8g246/T/sbt_8db2725a/xsbt/ExtractAPI.scala:479: error: java.util.Comparator does not take type parameters
  private[this] val sortClasses = new Comparator[Symbol] {
                                      ^
```

**Comment by estezz** [comment]
10:15:30-uwoesle~/workspace/iglu/2-repositories/scala-repo-server(master)$ sbt version
[info] Loading project definition from /Users/uwoesle/workspace/iglu/2-repositories/scala-repo-server/project
[info] Set current project to iglu-server (in build file:/Users/uwoesle/workspace/iglu/2-repositories/scala-repo-server/)
[info] 0.2.0
10:15:40-uwoesle~/workspace/iglu/2-repositories/scala-repo-server(master)$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by chuwy** [comment]
Hey @estezz,

This is because Scala <2.10.4 is incompatible with Java 8. To solve this you need update `scalaVersion` to `2.10.6`. But this also may not work - we highly recommend you to use our [Vagrant setup](https://github.com/snowplow/iglu/blob/master/Vagrantfile) - it should have all required components at their appropriate versions.

Also, please post questions on our [Discourse](http://discourse.snowplowanalytics.com/), Github issues for bugs only.
