### ISSUE TITLE
Common: add Ruby client

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#230]
Was implemented as part of of storage targets refactoring in https://github.com/snowplow/snowplow/issues/2991 and https://github.com/snowplow/snowplow/issues/2992.

**Comment by alexanderdean** [comment]
Cool, I've made you admin on https://github.com/snowplow/iglu-ruby-client @chuwy

**Comment by chuwy** [comment]
Wondering if @oguzhanunlu can also make Iglu Ruby Client 0.2.0 release? This can help with @BenFradet's idea about OSS PRs clean-up in Snowplow.

**Comment by alexanderdean** [comment]
Yes sure thing, please get this on his plate.
