### ISSUE TITLE
igluctl: switch severity level to skip checks

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#232]
Currently severity *levels* assume that we can have better or worse (high quality/low quality) checks, whereas it really not high/low, but include/exclude. User should have an ability to disable/enable each particular check if he is sure that absence of `maxLength` is fine.

My idea is to switch severity *levels* with checks option (or even `--skip-checks`), so user will have explicitly skip some lint if he wants: `igluctl lint /path/ --skip-checks optionalNull,implicitMax`, where `optionalNull` disables #231 check and `implicitMax` disables #175.

**Comment by chuwy** [comment]
Hey @oguzhanunlu, here's another piece of info.

Yes, we're going to get rid of notion of levels entirely as well as of `--severityLevel` option and instead skip each linter individually. Otherwise your approach looks quite correct.

You can have a map of linters:

```scala
val allLinters: Map[String, Linter] = Map(
  "minimumMaximum" -> lintMinimumMaximum,
  "minMaxLength" -> lintMinMaxLength,
...etc)
```

Then just get `Linter`s by their keys from provided input:

```scala
val lintersToUse = lintersToSkip.foldLeft(Right(allLinters.values)) { (linters, cur) =>
  (linters, allLinters.get(cur)) match {
    case (Right(linters), Some(c)) => Right(linters.diff(List(c)))
    case (Left(errors), Some(_)) => Left(errors)
    case (Right(_), None) => Left(List(s"Unknown linter $cur"))
    case (Left(errors), None) => Left(s"Unknown linter $cur" :: errors)
  }
}
```

**Comment by alexanderdean** [comment]
> I'm also quite keen to have different sets of linters for different use cases

That's a nice idea.

**Comment by chuwy** [comment]
Hey @oguzhanunlu, just a quick reminder to add description of all new linters Igluctl wiki page ("Update documenation" card in project this time is after you!)
