### ISSUE TITLE
RFC: igluctl verification

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#234]
Given there are a few potential pitfalls when setting up components of self describing schemas what do you think about adding an additional command that performs some level of verification on the steps involved in setting up. This could include (not limited to):

- Check schemas have been uploaded to the S3
- Check JSON paths have been uploaded to S3
- Check Etags on both local (repository) and remote (S3) files match
- Tables for each schema have been created in Redshift
- Tables for each schema are owned by the correct user (storageloader)
- Tables for each schema are the latest version according to the contents of the `sql` directory

**Comment by chuwy** [comment]
Hey @miike!

This sounds like a reasonable idea. Not sure if everything will belong to same command though or even specifically to `igluctl`, but overall this checks should reduce manual labor. Do you have any ideas/proposals about CLI UX?

**Comment by miike** [comment]
I imagine this looking something like running a test suite for a codebase only these probably fall under an integration test style framework. At the moment I've got a script mocked up that does something similar and provides ticks/crosses for passing/failing factors.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/41
