### ISSUE TITLE
igluctl: support REVISION migration for properties becoming nullable

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#238]
Migrated from https://github.com/snowplow/schema-guru/issues/147

**Comment by poberherr** [comment]
Is this fixed?

I had problems with this too, now figured out a solution.
But IMHO this is one of the core aspects of your framework. So 👍

**Comment by alexanderdean** [comment]
It's not ready yet - but agree it's important!

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/40
