### ISSUE TITLE
Schema DDL: placeholder for supporting migration cases

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#241]
Migrated from https://github.com/snowplow/schema-guru/issues/140

**Comment by chuwy** [comment]
Here I'm collecting possible Schema-migrations and ways to handle it
1. New optional property (column) added. Addition. Will be [implemented](https://github.com/snowplow/schema-guru/issues/134) in 0.6.0. 

``` sql
ALTER TABLE ADD COLUMN ...
```
2. Property become nullable. Revision. See #147

``` sql
ALTER TABLE ADD COLUMN customer_id_new string null;
INSERT INTO customer_id_new SELECT from customer_id;
ALTER TABLE DROP COLUMN customer_id;
ALTER TABLE RENAME COLUMN customer_id_new TO customer_id
END TRANSACTION;
```
3. Property become union-type: `string -> [string, number]`. Revision.  See #137 


4. A default is added to a property (Addition)
5. A minimum and/or maximum value is removed from a numeric (Revision)
6. New required field added (Model)

**Comment by alexanderdean** [comment]
7. New required field added with default (Revision?)

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/32
