### ISSUE TITLE
igluctl: check that proper content-encoding is set for unicode characters

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#249]
More info: http://discourse.snowplowanalytics.com/t/etl-shred-is-consistently-failing/1082/4

Either igluctl or scala server bug.

**Comment by chuwy** [comment]
De-scheduling this as we didn't confirm this was a bug.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/37
