### ISSUE TITLE
Schema DDL: support oneOf property

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#250]
JSON Schema with this property:

```json
      "ipaddress": {
        "type": ["string", "null"],
	"oneOf": [ { "format": "ipv4" }, { "format": "ipv6" } ]
      }
```

Cannot be converted into DDL with because of following failure:
`Error: Function - 'processList' - Invalid JValue: JObject(List((format,JString(ipv4)))) in list in [com.acme/event/jsonschema/1-0-2] Schema`.

As a result type we can use `VARCHAR(len(ipv6))` as greatest common factor.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/25
