### ISSUE TITLE
Schema DDL: Support multipleOf

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#251]
Should Iglu support multipleOf in JSON schemas?

This would open the door for Iglu to generate Schema DDLs that have a defined precision and switch from 15 digits of precision using`DOUBLE PRECISION` to variable precision using `DECIMAL(precision,scale)`.

**Comment by chuwy** [comment]
Yes, it definitely should. And it already has some support - it transforms `number` with `multipleOf: 1` to `integer` and `number` with `multipleOf: 0.01` to `DECIMAL(36, 2)`, which is I believe most common case.

What we want here is to extend this support to any `multipleOf: 0.n1` (n is arbitrary number of zeros), which is I agree very good idea.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/24
