### ISSUE TITLE
Schema DDL: add linter for optional fields

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#252]
As one more optional linter check (known as severity level now, but we want to change level-notation) we can ensure user defines non-required properties by `type: null`, not by omitting it in `required`.

Generally `null` and non-required property are same thing, but `null` has some advantages: 
* schema-derivation tools (like in Spark DataFrame) could end up not knowing about missed property and job would fail with runtime exception
* it shows that developer is really aware of optional property, not just forgot it
* it's easier to use `null` with template languages

**Comment by alexanderdean** [comment]
Agree, I much prefer `null` and it's much closer to the semantics of database DDL, schema languages and option types...
