### ISSUE TITLE
RFC igluctl: Should igluctl contain functionality to run SQL/DDL statements?

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#255]
Should igluctl contain some functionality (`igluctl static create`) to run generated SQL statements?

My main motivation is that this reduces the UX friction in using igluctl to deploy the schemas/JSON paths to Iglu but then having to switch tooling to run a SQL statement.

Initially this makes sense for Redshift but could also be extended to other data sources (Postgres, SQL Data Warehouse etc). This may(?) mean that igluctl can reconsume the configuration file for emr-etlr-runner.

**Comment by alexanderdean** [comment]
Hey @miike - it's a really interesting idea. Our plan was to "jump" to the DDL being auto-applied inside the Snowplow storage sinks, but thinking about it, that code has to live somewhere and arguably it c/should live in an Iglu component. One thing to be careful of here is that suddenly we are bundling database drivers into Iglu...

Needs some further rumination. Assigning to @chuwy for his thoughts.

**Comment by miike** [comment]
Agreed - there's definitely the potential of introducing a bit of bloat into an otherwise lightweight tool by introducing drivers.

**Comment by alexanderdean** [comment]
One to ponder! In general though, yes, we are committed to making things which sit somewhere on the Snowplow-Iglu border as generalized as possible, and thus landing them in Iglu territory...

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/36
