### ISSUE TITLE
Scala Core: add consumer-compatibility checks

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#269]
See https://github.com/snowplow/snowplow/issues/3459#issuecomment-335876237

In core this functionality can be as simple as:

```scala
type Consumer = String
type ConsumerMatrix = Map[Consumer, List[SchemaCriterion]

def compatible(matrix: ConsumerMatrix)(igluSchema: SchemaKey) = ??? // Compatible | Incompatible | Warning
```

Functionality that compares two schemas and decides if second one is model/revision/addition-bump is separate and should be in Schema DDL (couldn't find a ticket, but it's a number 3 in https://github.com/snowplow/iglu/issues/263)

**Comment by chuwy** [comment]
Pushing this back as not critical for this release.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-scala-core/issues/23
