### ISSUE TITLE
Schema DDL: Associate descriptions with generated SQL comments

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#270]
Given that #266 adds support for the description property to igluctl it seems like it would be nice to have igluctl consume that description and use it to generate `COMMENT ON` statements for each individual column in a Redshift table. This would enable end users to retrieve and describe table columns directly from Redshift rather than referring to a JSON schema.

Thoughts?

**Comment by alexanderdean** [comment]
Cool idea!

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/21
