### ISSUE TITLE
igluctl: fix incorrect generation of Redshift and JSON Path filenames

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#271]
For input `com.acme/event-with-dashes/jsonschema/1-0-0`, `static generate` outputs `event-with-dashes_1.sql` and `event-with-dashes_1.json`  files, which should have underscores instead of dashes to be consistent with StorageLoader and RDB Loader.

**Comment by alexanderdean** [comment]
Use the bug label when we find a bug!

**Comment by oguzhanunlu** [comment]
@chuwy I think [this commit](https://github.com/snowplow/iglu/pull/280/commits/11feaff01234e25dd9bc6e8a525452fc887ba059) handles both #265 and this issue. I tested your input and outputs look good.

1.  How should commit message look like? (Should I include this issue number as well?)
2. Should I include this issue in PR checkbox list/CHANGELOG as well?

**Comment by oguzhanunlu** [comment]
Since this issue's fix also handles #265 & #226, I closed them manually and let this one stay since its name is the best among three to stay in commit log.

**Comment by alexanderdean** [comment]
Can we come up with a better name for this ticket? It's a bit messy/confusing

**Comment by oguzhanunlu** [comment]
@alexanderdean  What about `igluctl: fix incorrect generation of Redshift table names and JSONPath filenames` ?

**Comment by alexanderdean** [comment]
Is it the Redshift table name? Or the filename?

**Comment by oguzhanunlu** [comment]
@alexanderdean I checked again and it is a problem with filename, not table name.

**Comment by alexanderdean** [comment]
Good, added a space in JSON Path
