### ISSUE TITLE
Schema DDL: Additional formats with type suggestions

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#274]
I've been developing some schemas recently and thought it would be nice to add some additional string formats that hint to defined length varchars including md5, sha1, sha256 etc. This might also be useful for GDPR column lengths that are pseudoanonymised.

**Comment by chuwy** [comment]
Is it same as https://github.com/snowplow/iglu/issues/170?

**Comment by miike** [comment]
Yes - it'd be custom formats that don't officially exist in the v4 spec.

**Comment by chuwy** [comment]
Ok, I'm quite big fan of this idea.

Leaving ticket as a placeholder for first group of these formats in Redshift DDL.

**Comment by alexanderdean** [comment]
Cool idea!

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/20
