### ISSUE TITLE
Documentation: Fix broken link on client configuration page

### ISSUE THREAD

**Issue by miike** [snowplow/iglu#277]
Fix the broken link 'repository resolution algorithm' on the https://github.com/snowplow/iglu/wiki/Iglu-client-configuration to point to https://github.com/snowplow/iglu/wiki/Schema-resolution#priority

**Comment by alexanderdean** [comment]
Thanks, scheduled!

**Comment by oguzhanunlu** [comment]
Updated [wiki](https://github.com/snowplow/iglu/wiki/Iglu-client-configuration) and closing this issue.
