### ISSUE TITLE
igluctl: bump AWS SDK S3 to 1.11.250

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#279]
We're not able to upload (`s3cp`) schemas to some regions added after our release.

**Comment by oguzhanunlu** [comment]
In https://github.com/seratch/AWScala/releases page, last release is 0.6.1 not 1.11.210 thus I change the title.

**Comment by chuwy** [comment]
Nope, AWScala is different project, a wrapper for AWS SDK, which transitively brought outdated AWS SDK in current version of Igluctl. In fact, I would like to factor out AWScala from Igluctl, because:

1. It adds outdated transitive AWS SDK
2. In the end, "AWS SDK on the Scala REPL" (from their README) which is not our case.
3. All modules we use from AWScala can be easily substituted with plain AWS SDK, almost without boilerplate. I see no real benefit.

My proposal here:

1. Add explicit [AWS SDK 1.11.228](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk) to dependencies. It'll override transitive (yet still binary-compatible) one from AWScala
2. If time allows in the end - factor out AWScala entirely (please, add un-milestoned ticket)
