### ISSUE TITLE
Scala Core: Incompatible Scala version breaks builds

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#284]
See #268 and #280 comments for this.

@chuwy , how should we proceed to avoid breaking builds?

**Comment by chuwy** [comment]
Hey @oguzhanunlu, could you provide more context here? I pulled `release/r7` and successfully compiled and tested Scala Core across all Scala versions and Json4s 3.2.11.

**Comment by oguzhanunlu** [comment]
Hi @chuwy , your successful compile is due to commit update fixing the problem. If you look at [this commit](https://github.com/snowplow/iglu/commit/43e2dc779e81704a5c915ae435eec825b750541f) and [its build log on travis](https://travis-ci.org/snowplow/iglu/builds/300073622) , existing scala version `2.10.1` isn't compatible reading Java 8 compiled classes. Kafka had a similar issue [here](https://issues.apache.org/jira/browse/KAFKA-1624) . Thus I bumped scala version to `2.10.6` to build successfully.

I opened this issue after your last review on #280  which includes a request to open an issue to discuss this since temporary scala version bump isn't expected in #268 .

**Comment by chuwy** [comment]
I believe we have some misunderstanding here.

Your first commit points to dependencies of `0-common/scala-core`. Your second link points to output of `2-repositories/scala-repo-server` (which is only project tested automatically by Travis CI). So with or without [43e2](https://github.com/snowplow/iglu/commit/43e2dc779e81704a5c915ae435eec825b750541f) I'll be able to compile and test Scala Core.

It means that everything is fine with Scala Core, it compiles, there's no incompatibilities, but instead problem is in Scala Repo Server and that's what I meant in that comment, sorry for not being clear.

**Comment by oguzhanunlu** [comment]
Aah, of course, you're right. Sorry that I took a misstep. Will fix per our conversation.

**Comment by chuwy** [comment]
Hey @oguzhanunlu, should it be closed in favor of https://github.com/snowplow/iglu/issues/289?

**Comment by oguzhanunlu** [comment]
Of course, it was my mistake, let me close it.
