### ISSUE TITLE
Scala Core: bump sbt-bintray to 0.5.1

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#285]
As noted in their [README](https://github.com/sbt/sbt-bintray#what-you-need) , both the plugin organization and the name has changed in 0.4.0 .

I'll bump to `0.5.1`, their [latest release](https://github.com/sbt/sbt-bintray/releases/latest)

**Comment by chuwy** [comment]
Was there something broken in sbt-bintray? If wasn't - please us just `Scala Core: bump sbt-bintray to 0.5.1` as "fix" implies some kind of wrong behavior.

**Comment by oguzhanunlu** [comment]
No, nothing broken. You're right, thanks @chuwy !
