### ISSUE TITLE
igluctl: switch to Scala 2.12

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#287]

**Comment by chuwy** [comment]
Hey @oguzhanunlu, can we change this to `igluctl: switch to Scala 2.12`. I don't know what was the reason I made it compiling with different versions of Scala - this is an end-user application, not a library, if it compiles with 2.12 - we don't need 2.11 and 2.10.

**Comment by chuwy** [comment]
Also, add please following options https://github.com/snowplow/snowplow-rdb-loader/blob/master/project/BuildSettings.scala#L34-L57

**Comment by oguzhanunlu** [comment]
Of course @chuwy, I'm on it.
