### ISSUE TITLE
Scala Core: bump to 0.2.0

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#292]
This is just to bump `version` in `BuiildSettings`/`build.sbt`.

**Comment by chuwy** [comment]
Sorry @oguzhanunlu. Fixed title.

**Comment by oguzhanunlu** [comment]
Please ignore [last commit](https://github.com/snowplow/iglu/commit/905beecc598b409dde6b2a07f95afa94bccca0a5), I mistakenly referenced this issue.

**Comment by chuwy** [comment]
@oguzhanunlu could you please also add name `iglu-core-json4s` (and others) to SBT configuration. Right now we've [changed](https://github.com/snowplow/iglu/commit/7db1b4c7c84378079fb5f9886772f93b0841bcdc#diff-4d3913df2c00ecb03db5d54b9568ce4eL30) name to `igluclurejson4s` (in wrong commit, btw) in dependency. But we cannot rename whole artifact (basically a project name) on minor version bump.
