### ISSUE TITLE
Explore single Dependencies.scala file

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#299]
Since iglu/0-common contains 3 sub-projects which have project-level dependencies between them (e.g. igluctl uses schema-ddl), it is possible to encounter binary incompatibilities due to transitive dependencies of two projects.

I faced a very similar situation to the following; among igluctl dependencies, we have `scalaz-7.0.8` and schema-ddl which depends on `scalaz-7.1.1`. SBT will pick higher version, `7.1.1`. Let's say we used, in igluctl, a function from `scalaz-7.0.8` which doesn't exist in `scalaz-7.1.1`. Since `scalaz-7.1.1` isn't binary compatible with `scalaz-7.0.8`, we will have errors.

Why don't we use a common Dependencies.scala file instead of dealing with multiple Dependencies.scala files? Wouldn't it be easier to track dependencies across subprojects?

**Comment by alexanderdean** [comment]
Interesting idea! How would this work in practice?

**Comment by oguzhanunlu** [comment]
@alexanderdean I was thinking of having a `CommondDependencies.scala` file at `0-common/` containing a `Global` object, combination of all `V` objects in `Dependencies.scala` files. Projects would specify library versions through accessing this `Global` object instead of currently used `V` objects residing in subproject-specific `Dependencies.scala` files.
e.g. `Global.scalazSpecs2` instead of `V.scalazSpecs2` for `schema-ddl`.

This will make sure only one version of a library will be used across `iglu/0-common` subprojects.

**Comment by chuwy** [comment]
That unfortunately will require to turn Iglu into SBT-project, which might be to involved. But I agree that idea is worth to explore.

**Comment by alexanderdean** [comment]
Interesting idea...

**Comment by chuwy** [comment]
I think single `Dependencies.scala` is quite ad-hoc solution for a minor problem, caused by few very outdated libraries. Instead of relying on big changes like this, it would be much better just to keep libraries up-to-date.
