### ISSUE TITLE
Command-line client for Iglu

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#30]
Great idea by @BenFradet - essentially would allow you to publish, test and fetch schemas from the command-line.

If we write in node.js, then a) deployment is really easy (vs Ruby or Python) b) it will be responsive (vs JVM and c) we can extract out a node.js client

**Comment by chuwy** [comment]
Implemented as https://github.com/snowplow/iglu/issues/143, https://github.com/snowplow/iglu/issues/144
