### ISSUE TITLE
igluctl: add support for Java 9

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#300]
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by chuwy** [comment]
Bringing it forwards. @oguzhanunlu  please test and close if it was already fixed.

**Comment by oguzhanunlu** [comment]
Currently, scalac `2.12.4` doesn't support jvm 9 as target. Running `scalac -target` under `igluctl/` gives following:

```
scalac error: Usage: -target:<target> where <target> choices are jvm-1.5, jvm-1.6, jvm-1.7, jvm-1.8 (default: jvm-1.8)
```

Assembled igluctl and tested few schemas using JRE 9 on localhost and they worked fine. De-scheduling this issue for now.

**Comment by chuwy** [comment]
> Assembled igluctl and tested few schemas using JRE 9 on localhost and they worked fine. De-scheduling this issue for now.

It basically means that Java 9 support was added implicitly by some another ticket (most likely #287). Leaving open so far to check if anyone else will hit this issue.

**Comment by carabaestlein** [comment]
I ran into this last week trying to push schemas to S3 using igluctl (version 0.3.0):
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```
I could only resolve it when I downgraded to Java 8.

**Comment by chuwy** [comment]
Thanks @carabaestlein! @oguzhanunlu can we please do one of following:

1. Figure out what brings `javax/xml/bind` and remove/update this dep
2. Follow **Proper long-term solution** instructions on link @alexanderdean provided.

Also we'll have to test all subcommands next time.

**Comment by oguzhanunlu** [comment]
Thanks for pointing this out @carabaestlein ! Alright @chuwy , I'll resolve it when I get back.
