### ISSUE TITLE
Schema DDL: decide if AST can be parsed with invalid values

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#301]

**Comment by chuwy** [comment]
Let's leave it out of scope of R7. We're not using Schema AST extensively and right now invalid values make sense. Though if I remember right there's some inconsistencies between these: `maxItems` `maxLength` etc

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/19
