### ISSUE TITLE
Schema DDL: add JSON Schema Draft v7 support

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#303]
http://json-schema.org/draft-07/json-schema-release-notes.html#formats

In validation there's few new formats, most useful of which include: `date`, `time`, `regex`. 

Requires corresponding ticket in Iglu client when implemented. 

See also: https://github.com/snowplow/iglu/issues/170

**Comment by jethron** [comment]
Would love this sooner rather than later; some super useful features in the newer drafts. Particularly "examples" and "const" are awesome, but throw errors in Igluctl and mark schemas as invalid.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/18
