### ISSUE TITLE
igluctl: drop version and extension from executable filename 

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#308]
Hey @oguzhanunlu, could you please prioritize this for 0.4.0? Reach me if you need help - this is a very quick thing to do.

**Comment by chuwy** [comment]
Should be `igluctl_0.3.0.zip/igluctl` instead of `igluctl_0.3.0.zip/igluctl-0.3.0.jar`.

**Comment by oguzhanunlu** [comment]
Sure @chuwy , I'll.
