### ISSUE TITLE
igluctl: update documentation

### ISSUE THREAD

**Issue by carabaestlein** [snowplow/iglu#310]
Can we update the [documentation](https://github.com/snowplow/iglu/wiki/Igluctl#2-quickstart) to reflect the newest version (0.3.0)? 

Also can we highlight that using igluctl is now different:
 
```
$ ./igluctl-0.3.0.jar --help
``` 
instead of 
```
$ ./igluctl --help
``` 

and that [lint](https://github.com/snowplow/iglu/wiki/Igluctl#3-lint) has `--severityLevel 3` available?

Thanks!

**Comment by chuwy** [comment]
Thank you! Updated all docs. Closing this.
