### ISSUE TITLE
igluctl: add Redshift DDL migrations

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#312]
In near future we'll have remove all old manually created DDLs from Iglu Central, which means we'll have to create diffs/migrations from manually created to Igluctl-created. 

Depends on https://github.com/snowplow/iglu/issues/311

**Comment by chuwy** [comment]
Another way here would be to bump model in all tables, but then all existing trackers will keep sending data for old tables, so I'm all for parser and migrations approach.

**Comment by bernardosrulzon** [comment]
It would be great to leverage the impact of ZSTD encodings as well: https://github.com/snowplow/iglu/issues/237

**Comment by alexanderdean** [comment]
> I'm all for parser and migrations approach

Me too.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/34
