### ISSUE TITLE
igluctl: fix false failure message in push command

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#313]
When overriding an existing schema with 0.3.0 we're getting this error:

```
FAILURE: {
  "status" : 200,
  "message" : "Schema successfully updated",
  "location" : "/api/schemas/com.acme/event/jsonschema/1-0-0"
}
```

But upload actually works. 0.2.0 works without problems. It seems that problem is that Igluctl cannot deserialize above message into [ServerMessage](https://github.com/snowplow/iglu/blob/5665866b079d36a5a70a55d51014c929070f1b6e/0-common/igluctl/src/main/scala/com.snowplowanalytics.iglu/ctl/PushCommand.scala#L234) and ends up in [this branch](https://github.com/snowplow/iglu/blob/5665866b079d36a5a70a55d51014c929070f1b6e/0-common/igluctl/src/main/scala/com.snowplowanalytics.iglu/ctl/PushCommand.scala#L308-L309).

@oguzhanunlu, I believe this is same kind of problem we had with JSON Schema AST. Was that method also called `asString`?

**Comment by oguzhanunlu** [comment]
@chuwy , there were 2 methods and one of them was [`toString`](https://github.com/snowplow/iglu/commit/0b83d83bfcc8f949bf3a20c9955a72e3e6f2e8ac#diff-6c1a477f49f615aa18acae16bedf6eadL66) .

**Comment by chuwy** [comment]
Hey @oguzhanunlu, just as heads-up, could you please check all iglu subprojects with Scala 2.12 for this json4s-extraction bug? 

```bash
$ cd 0-common
$ grep -r extract\[ .
```

...or similar. We don't want to hit this in other places.

**Comment by oguzhanunlu** [comment]
@chuwy , trying to reproduce, I can't assemble scala repo server, I get `java.lang.NoSuchMethodError: sbt.Keys$.compatibilityWarningOptions()Lsbt/SettingKey` error after running `sbt assembly`. I use java 7 as pointed [here](https://github.com/snowplow/iglu/wiki/Install-the-Scala-repository-server#1-dependencies) . I wanted to download its jar directly but it is [not specified](https://github.com/snowplow/iglu/wiki/Install-the-Scala-repository-server#21-download-the-executable-jarfile) yet. Can you assemble?

**Comment by chuwy** [comment]
@oguzhanunlu our compiled assets available at http://dl.bintray.com/snowplow/snowplow-generic/ (please fix the wiki page, also). 

Problem most likely that you have SBT 1.0, while repo uses very old one. To avoid issues like this, please use `Vagrantfile` from project root. This is supposed to be default approach.

**Comment by oguzhanunlu** [comment]
@chuwy Your first assumption is true. Problem is `asString`. I also checked all Iglu subprojects for similar behavior and didn't encounter any.
