### ISSUE TITLE
igluctl: add check for unknown files in tree

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#314]
See https://github.com/snowplow/iglu-central/pull/697#issuecomment-357183172

If someone misplaces schema into:

```
+ schemas/
  + com.acme/
    + event/
      + 1-0-0
```

instead of 

```
+ schemas/
  + com.acme/
    + event/
      + jsonschema/
        + 1-0-0
```

Igluctl does not recognize `1-0-0` as schema. Therefore we need to make sure that registry does not contain any other files apart from schemas (hidden files are fine, I suppose).

**Comment by knservis** [comment]
The only schemas currently in use are avro and jsonschema right? Does igluctl support avro?

**Comment by chuwy** [comment]
No, it doesn't. There's also thrift, which is also not supported. But I don't see it makes any difference.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/33
