### ISSUE TITLE
Scala Core: port successor detection from igluctl

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#315]
Current implementation for #221  can be refactored to bring exciting adjustments to Iglu per @chuwy 's [suggestions](https://github.com/snowplow/iglu/pull/309#pullrequestreview-89702921). I'm excited about these ideas and will realize soon.

**Comment by chuwy** [comment]
Clarified ticket little bit. 

Whole idea is to provide more general implementation and therefore place into Scala Core or Schema DDL.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-scala-core/issues/22
