### ISSUE TITLE
igluctl: add WartRemover

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#316]
http://www.wartremover.org/doc/warts.html

Hey @oguzhanunlu I'm planning to check this out over this weekend. If it goes well - I'm keen to enable it for all subprojects (which will be up to you in next releases).

Similar Snowplow-ticket: https://github.com/snowplow/snowplow/issues/3586

**Comment by BenFradet** [comment]
maybe we should standardize on scalastyle given that it's been done in snowplow and also scalastyle seems to be more active than wartremover lately

**Comment by chuwy** [comment]
Hm, it probably makes sense. I'm also leaning towards ScalaStyle, but would like to do a research.

**Comment by oguzhanunlu** [comment]
Thanks for letting me know @chuwy , it seems ScalaStyle outweighs WartRemover but I'll also take a look at both options, especially community opinions and development activeness.

**Comment by chuwy** [comment]
So, after trying out both I have following conclusions:

1. ScalaStyle and WartRemover are actually different tools, intersection of their lintings is very small. ScalaStyle is for plain formatting: indentations, newlines, absense of "magic numbers". It works with text and knows nothing about code, its types etc, e.g. it doesn't warn you about `Option#get`, `List#head` and similar while WartRemover does, as well as many similar "mistakes" such as coercing to `Any`, using Scala `Enumerations` and many other - almost all of them are missing in ScalaStyle.
2. Lots of false positives and just annoying warnings (like "All public members should have explicit types" in test specification) in both, especially when IDE also tries to perform these checks. While it is fine for Iglu - it is simply impossible to clean everything up in snowplow/snowplow.
3. Having above two points I decided to not include non of them as SBT plugins and instead using them as standalone tools and mention it in CONTRIBUTING guide https://github.com/snowplow/snowplow/issues/3530

**Comment by chuwy** [comment]
Docker image with latest SBT and both linters would be useful.

**Comment by BenFradet** [comment]
btw WartRemover rules are being integrated into scalafix: https://github.com/scalacenter/scalafix/issues/529

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/32
