### ISSUE TITLE
igluctl: fix the bug resulting in redudant characters after JSON closing brace

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#317]
Imagine following file:

```
{
  "key": "value"
}
}
```

When it is "pretty-printed", json4s (and igluctl and other tools) simply ignore redundant closing brace. But when it is "compact-printed" (`{"key":"value"}}`) it becomes invalid JSON.

This is a known bug in json4s parser's behavior. I think the only way to fix it is to upgrade/replace json4s.

**Comment by alexanderdean** [comment]
Is there a link to the underlying json4s bug?

**Comment by chuwy** [comment]
Couldn't find it (it is actually jackson's issue, not json4s'), but I know that developers are aware of this behavior.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/31
