### ISSUE TITLE
Server: embed online iglu client

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#326]
There's awesome iglu-compatible online client at http://jsonschema.help/

We can embed it if @premjg doesn't mind or have Scala Iglu Client backed backend.

**Comment by alexanderdean** [comment]
Neat idea

**Comment by chuwy** [comment]
This also can be Snowplow Mini ticket. I feel it belongs to iglu, but don't have a strong opinion.

**Comment by premjg** [comment]
@chuwy @alexanderdean - Feel free to use it however you chose fit. Happy to contribute to Snowplow. (I'm a big fan)

Let me know what support you need from me.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-server/issues/20
