### ISSUE TITLE
igluctl: provide more information about failed upload

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#328]
For `static push` this should include:

instead of 

```
FAILURE: java.net.SocketTimeoutException: connect timed out
```

This should be 

```
FAILURE: java.net.SocketTimeoutException: connect timed out for http://iglu.acme.com:8081/api
```

**Comment by poberherr** [comment]
I am suffering from a case with the same error, where randomly events are uploaded and other times events are not uploaded at all ( to snowplow mini ).

It stays completely blurry what is failing; which is a blocking issue for me.

**Comment by chuwy** [comment]
Hey @poberherr, there's not many points of failure for `static push`. It is either connection between your computer and EC2 box with Snowplow Mini or Snowplow Mini is being under heavy load. But I agree, message should be more clear.

**Comment by chuwy** [comment]
Scheduling it for next release, @oguzhanunlu, should be low-hanging fruit.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/29
