### ISSUE TITLE
igluctl: add linter for properties with default present in required

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#336]
Following schema doesn't make sense:

```
{
  "properties": {
    "foo": {
      "default": 0,
    }
  }
  "required": "foo"
}
```

Because `default` implicitly makes property non-required.

See https://github.com/snowplow/iglu-scala-client/issues/76#issuecomment-364375880

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/30
