### ISSUE TITLE
igluctl: add linter for named properties' coherence with required and additional properties

### ISSUE THREAD

**Issue by knservis** [snowplow/iglu#337]
See https://github.com/snowplow/iglu-central/issues/700#issuecomment-364378725

**Comment by chuwy** [comment]
Hey @knservis, "logical impossibilities" is exactly what igluctl linter catches. We're talking here about particular impossibility that we need to add.

**Comment by alexanderdean** [comment]
Yes, ticket title is poor

**Comment by knservis** [comment]
How's that?

**Comment by alexanderdean** [comment]
What's a specified property in JSON Schema?

**Comment by chuwy** [comment]
I think example here would be usefule:

```json
{
  "key1" : "object"
  "properties": {
    "key2": {
      "type": "string"
    },
    "key3": {
      "type": "string"
    }
    oneOf: [
      "required": ["key4", "key3"],
      "required": ["key4", "key2"]
    ],
    "additionalProperties": "false"
  }
}
```

**Comment by knservis** [comment]
@alexanderdean I updated the title to qualify that these are all object type members.

**Comment by knservis** [comment]
@alexanderdean By specified properties I mean the set of the object properties specified in the schema definition.

**Comment by alexanderdean** [comment]
Shortened it

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/27
