### ISSUE TITLE
igluctl: fix interpreting SchemaVer warnings as failures

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#340]
`igluctl lint` command checks versions of schemas in input. 

In case input is the full path to schema and schema's version isn't `1-0-0`, it should give a warning. However, `igluctl v0.4.0` produces failure message instead of warning.

This bug will result in encountering failure messages instead of warning messages where input is full path to schema and its version isn't `1-0-0`.

**Comment by chuwy** [comment]
Thanks. We need to prioritize it unfortunately, as linting single new schema is most common operation.
