### ISSUE TITLE
igluctl: make lintOptionalNull report about all invalid properties

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#342]
Having this JSON schema:

```json
{
  "properties": {
    "a": {  "type": "string" },
    "b": {  "type": "string" },
    "c": {  "type": "string" }
  },
  "required": ["a"]
}
```

`igluctl lint` will print warning only once. This is maybe a good thing having how annoying these warning [without additional info](https://github.com/snowplow/iglu/issues/330), but message is misleading. It should state something like `Properties [b,c] are not required and don't allow null type`.

Also, this check doesn't work at all if there's no `required` schema property.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/26
