### ISSUE TITLE
igluctl: add linter for repeated JSON object keys

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#343]
Duplicated keys are valid in Json4s, Jackson and [implicitly in JSON specification](https://stackoverflow.com/a/23195243/998523), but clearly should be invalidated for our use case.

See https://github.com/snowplow/iglu-central/issues/732

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/25
