### ISSUE TITLE
Schema Registry: keep user authentication up to date

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#347]
Currently, users are authenticated through custom HTTP header `"apikey"`. I think we need to update our auth approach.

It is clear that akka-http is stricter than spray for authentication since all of [security directives](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/security-directives/index.html) in akka-http work only with `type Credentials` which is actually HTTP `Authorization` request header, not a custom HTTP header.

If we decide that auth mechanism better change, there are 2 types of Credentials supported by akka-http; (HttpGenericCredentials are [not supported](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala#L320)) 

- BasicHttpCredentials(username: String, password: String)
- OAuth2BearerToken(token: String)

Typically, Basic authentication is preferred for users while OAuth2 is for applications.

I'd naively propose going with Basic authentication but aim of this issue is discussing and deciding whether update auth mechanism or not followed by which auth mechanism to apply in case we decide to update.

Opinions appreciated.

@chuwy @alexanderdean

**Comment by alexanderdean** [comment]
I vote for basic for now, as it's a smaller change. Remember that this change will have repurcussions in Snowplow Mini and elsewhere, so we need to minimize the change given we need to get R9 out...

**Comment by oguzhanunlu** [comment]
@alexanderdean token authentication migration happened successfully just now with existing custom http header approach thanks to @chuwy 's help. It was a blocker and now I'm full speed ahead on R9. We can consider changing authentication mechanism later in iglu workshop.

**Comment by chuwy** [comment]
Hey @alexanderdean! This topic was intended to discuss a final solution for authentication that we will want to stick with for a very long time. Problem with akka directives was transient technical issue and we've already solved it. But whole point is that using custom header does not look optimal (rather ad-hoc) solution and we'll probably want to switch to something more convenient later. 

In this sense,  OAuth tokens (for interacting with Registry via Igluctl/Iglu clients etc) look very appealing. Definitely much more powerful (and complicted) and real question is whether we'll be able to find use cases.

We can afford only one such API change even in long-term (as lot of various apps already coupled with this API) and we don't want these changes to be driven by transient technical difficulties.

**Comment by chuwy** [comment]
One use-case: we can pass tokens with different ranges of permissions to different pipelines with embedded schema-inference. E.g. pipeline A can derive schemas for `com.acme` and publish them straight to registry, whereas schemas for `com.mailchimp` should be uploaded manually.

**Comment by alexanderdean** [comment]
Ah - I understand this ticket better now. Sorry, I understood from this morning that it was a blocker on R9.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-server/issues/19
