### ISSUE TITLE
igluctl: add linter config for precise skips

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#348]
This might be an over-complication for such a small one-time task as linting, but could make sense for registry CI/CD.

In particular, in Iglu Central we have only one schema with array root type and we have to skip this check for whole registry just to make CI/CD pass, while we should be able to skip this check only for this schema.

Config could be following:

```json
{
  "iglu:com.acme/event/jsonschema/1-0-0": {
    "skip-checks": {
      "$.path.to.array": ["rootObject", "unkownFormats"],
      "$.another.path": ["numericMinMax"],
    }
  }
}
```

IIRC @miike was interested in this feature. Mike do you have any proposals here?

/cc @knservis

**Comment by alexanderdean** [comment]
Interesting. I think the value depends a lot on how long we continue to emphasize schema registries in source control...

**Comment by chuwy** [comment]
Superseded by https://github.com/snowplow/iglu/issues/383

**Comment by chuwy** [comment]
Actually, re-opening. As first version won't include *precise* by-path skips.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/23
