### ISSUE TITLE
igluctl: avoid bucket/path issues

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/iglu#350]
If you point igluctl to a directory (either `./schemas` or `./jsonpaths`), the required input is just the bucket name. 

However, if you only want to upload one file (`./schemas/event_name/jsonschema/1-0-0`), you need to input `bucket_name/schemas`. Same goes for jsonpaths.

This has led to issues in the past with uploading to the wrong location, and in the case of jsonpaths can cause pipeline failures.

A future version of igluctl could have some kind of inference - if pointed to a file, look for the folder in the bucket, if it's a directory, look for the analogous folder in s3.

**Comment by alexanderdean** [comment]
Thanks for raising @colmsnowplow !

**Comment by alexanderdean** [comment]
Scheduling as this keeps coming up with Services.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/22
