### ISSUE TITLE
Schema Registry: switch swagger-ui deployment from static files to artifact

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#353]
Most common way of deploying `swagger-ui` to a project is by copying static files to your project and make some tweaks, in our case only `url` and `validatorUrl` settings in `index.html`.

To make use of compiled assets, some frameworks have support for webjars but akka-http doesn't. There is a 3rd party library not actively maintained [here](akka-http-webjars) with no doc.

We should handle this when akka-http supports webjars or Swagger community has a consensus. They currently [don't have](https://github.com/swagger-api/swagger-ui/issues/758).

**Comment by chuwy** [comment]
Totally makes sense.

**Comment by chuwy** [comment]
This has been done in 0.6.0.
