### ISSUE TITLE
Igluctl: provide meaningful error messages on unexpected Iglu Registry responses

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#354]
Currently, if registry responds not with expected `{"read": "key", "write": "key"}` JSON object, igluctl prints following message:

```
Did not find value which can be converted into java.lang.String
INFO: No keys were created
TOTAL: 0 Schemas successfully uploaded (0 created; 0 updated)
TOTAL: 1 failed Schema uploads
```

Which doesn't make a lot of sense. [This](https://github.com/snowplow/iglu/blob/master/0-common/igluctl/src/main/scala/com.snowplowanalytics.iglu/ctl/PushCommand.scala#L331) should be transformed into something more meaningful.

Also, I'd like to have a single source of truth for messages (responses) like this so clients and registries could have expectation on communication protocol. Something like `2-repositories/scala-registry-core`.

**Comment by chuwy** [comment]
This also happens for 404, which should be treated as another error.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/21
