### ISSUE TITLE
Schema resolution isn't playing ball

### ISSUE THREAD

**Issue by AlexCraddock** [snowplow/iglu#359]
Hello,

I have written a schema resolver

`{
  "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-1",
  "data": {
    "cacheSize": 1000,
    "repositories": [
      {
        "name": "Iglu Central",
        "priority": 0,
        "vendorPrefixes": [ "com.snowplowanalytics" ],
        "connection": {
          "http": {
            "uri": "http://iglucentral.com"
          }
        }
      },
      {
        "name": "Acme Iglu Repo (HTTP)",
        "priority": 5,
        "vendorPrefixes": [ "com.pubfactory" ],
        "connection": {
          "http": {
            "uri": "https://s3-eu-west-1.amazonaws.com/igluresolver"
          }
        }
      }
    ]
  }
}`

And I am trying to test it with an iglu url of iglu:com.pubfactory/myschema/jsonschema/1-0-0

Yet it keeps telling me it can't find the schema yet if I put in the url 
s
https://s3-eu-west-1.amazonaws.com/igluresolver/schemas/com.pubfactory/myschema/jsonschema/1-0-0 it downloads the file,

I am missing something but I am not sure what, 

Thanks,

Alex

**Comment by alexanderdean** [comment]
Hi @AlexCraddock - can you direct any support requests to our forums please:

https://discourse.snowplowanalytics.com/
