### ISSUE TITLE
Server: add baseURL to configuration

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/iglu#362]
Add a `repo-server. baseURL ` to indicate baseUrl of Swagger UI.

Background story: After dockerizing iglu server and deploying, it was seen that Swagger UI was using `repo-server.interface` as base URL and sending requests to `0.0.0.0` (coming from default docker network interface which we used when dockerizing iglu server) which is clearly not we want. After looking at Swagger community discussions, it is seen that Swagger UI 3.x doesn't offer ability to update `url` in `SwaggerUIBundle`. After discussions, @chuwy offered to add a deployment address to `application.conf` so that we can make sure Swagger UI is being generated with deployment address and send requests to expected address, not docker interface.

**Comment by chuwy** [comment]
...and comment in `application.conf`

**Comment by oguzhanunlu** [comment]
I'll @chuwy , I'll also update my first comment here with a more detailed explanation why it was needed.
