### ISSUE TITLE
igluctl: add static pull command

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#365]
Obviously reverse of `static push` to create static registry out of schemas from Iglu Server.

We have no convenient way to navigate through schemas on Iglu Server apart from `GET`ting one by one or inspecting array.

**Comment by chuwy** [comment]
Should have optional `--vendor` option (others as well `--format`, `--name` etc?)

**Comment by alexanderdean** [comment]
This should be really valuable for when somebody wants to work on a (new) schema in their local IDE.

**Comment by alexanderdean** [comment]
This is really important!

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/20
