### ISSUE TITLE
Schema DDL: Integrate scalafmt

### ISSUE THREAD

**Issue by szareiangm** [snowplow/iglu#376]
Similar to snowplow/snowplow-elasticsearch-loader#101 to help smooth code-reviews.

c.f. snowplow/scala-maxmind-iplookups@815677a for ref for the config

**Comment by saj1th** [comment]
could give it a try

**Comment by chuwy** [comment]
Hi @saj1th! Yes, that's exactly right. All projects in iglu monorepository are separate artifacts and have separate build configurations, so we're treating them accordingly.

**Comment by saj1th** [comment]
cool! would do that

**Comment by chuwy** [comment]
@saj1th just could you please open a PR against [release/0.6.0](https://github.com/snowplow/iglu-scala-client/pull/111)?

**Comment by saj1th** [comment]
@chuwy  is release/0.6.0 applicable for snowplow/iglu along with  snowplow/iglu-scala-client ?
Sorry If i'm missing something. For iglu I'm seeing release/r11 

Please shed some light

**Comment by chuwy** [comment]
@saj1th primary Iglu repository and Iglu client are not aligned in their versionings. We use Release-convention (`Rxx`) for mono-repositories (e.g. Iglu R11) and Version-convention (`x.y.z`) for common repositories (e.g. Iglu Client Version 0.6.0).

So, don't worry about that.

**Comment by saj1th** [comment]
@chuwy 
Let me try and rephrase it . Isn't [release/0.6.0](https://github.com/snowplow/iglu-scala-client/pull/111) for changes in snowplow/iglu-scala-client  only

Since snowplow/iglu is a different github repository, wondering how to open a PR for changes in snowplow/iglu against release/0.6.0

May be i'm missing something very basic here  👀

**Comment by chuwy** [comment]
Hey @saj1th, I'm very sorry about that, I indeed confused repositories, I thought this talk is happening in Iglu Client's one.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/15
