### ISSUE TITLE
igluctl: add validate subcommand

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#388]
Just a wrapper around Iglu Scala Client. Users often use Snowplow Mini only in order to validate their self-describing entities (events and contexts), though they are independent from enriched event and can be validated via CLI.

```
igluctl --resolver iglu_resolver.json --data context.json
```

* Resolver can be default to iglucentral-only
* Without `--data` it should be able to receive data from `stdin`
* `context.json` can contain NDJSON

Probably same functionality for Iglu Server would be nice, where resolver defaults only to current Registry.

**Comment by alexanderdean** [comment]
By a context do you just mean a self-decribing JSON? context is Snowplow language, not Iglu...

**Comment by alexanderdean** [comment]
Cool, make sure that help text doesn't refer to a context...

**Comment by chuwy** [comment]
Server ticket: https://github.com/snowplow/iglu/issues/326

**Comment by miike** [comment]
Big fan of this idea as it makes it'd make it a lot easier to have some of this run as part of continuous integration pipelines.

**Comment by chuwy** [comment]
CI/CD is a great point, @miike. We've just scheduled next (minor) release of Iglu, but I'm very keen to add this ticket into next one.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/19
