### ISSUE TITLE
Scala Core: Remove resolutionRepos from BuildSettings

### ISSUE THREAD

**Issue by szareiangm** [snowplow/iglu#390]
The code was not compiling. I will submit a pull request for it.

**Comment by chuwy** [comment]
What was the error, @szareiangm? It should compile as it was built and published?

**Comment by szareiangm** [comment]
Looks unusual to me, too. But that line has:
Dependencies.resolutionRepos
and there is no such thing in Dependencies.scala file:
https://github.com/snowplow/iglu/blob/develop/0-common/scala-core/project/Dependencies.scala

You removed that line your previous commit:
e7821c0#diff-fec9746d8dc3c96432f568d3c5623da4

**Comment by chuwy** [comment]
Right, desync is the problem of `develop` branch, I'll remove it as part of "bump SBT" commit. Thanks for heads-up!
