### ISSUE TITLE
ScalaCheck Schema DDL: add

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#392]
`scalacheck-schema-ddl` is a module responsible for generating self-describing JSON instances out of JSON Schemas. It has `schema-ddl` in name because it leverages typesafe JSON Schema AST from Schema DDL project.

/cc @BenFradet @asoltysik

**Comment by BenFradet** [comment]
I think it'd make sense to externalize it as a different repo as it can be useful to people not using iglu at all, I created https://github.com/snowplow-incubator/json-schema-gen as a placeholder (we can definitely find a better name)

**Comment by chuwy** [comment]
I have few counter-arguments (though I definitely prefer multi-repos):

1. It will depend on Schema DDL through JSON Schema AST and therefore several other Iglu libs (Scala Core at least)
2. I was planning to add Iglu Client shortcuts to generate schemas out of remote registries

**Comment by BenFradet** [comment]
>It will depend on Schema DDL through JSON Schema AST and therefore several other Iglu libs (Scala Core at least)

why does this make having it in this repo mandatory?

>I was planning to add Iglu Client shortcuts to generate schemas out of remote registries

same as above. Additionally this seems a bit out of the original scope to me. It'd better fit as a submodule, wdyt?

---
I'd argue that incorporating it to this repo will completely prevent wide-spread usage (SEO will be awful).

**Comment by alexanderdean** [comment]
> I'd argue that incorporating it to this repo will completely prevent wide-spread usage (SEO will be awful).

That's not in any way our priority though. Our priority is launching a BigQuery Loader for GCP - whatever is faster to that end.

**Comment by chuwy** [comment]
> why does this make having it in this repo mandatory?

Not mandatory at all. It was the point regarding people not using Iglu - there will be huge part of Iglu anyway. As of actual repo - ok, I'm moving it to same https://github.com/snowplow-incubator/json-schema-gen, I think it will be faster to keep it out of main repo.

**Comment by chuwy** [comment]
...or actually https://github.com/snowplow-incubator/scalacheck-schema

**Comment by alexanderdean** [comment]
> scalacheck-schema

Nice name
