### ISSUE TITLE
Scala Core: swap SelfDescribingData member names

### ISSUE THREAD

**Issue by knservis** [snowplow/iglu#394]
https://github.com/snowplow/iglu/blob/8d333417a8e03ad1b9bf11d61211dd3fbd4ab17d/0-common/scala-core/src/main/scala/com.snowplowanalytics.iglu/core/SelfDescribingData.scala#L22

**Comment by miike** [comment]
@chuwy What values does this refer to swapping? SelfDescribingData => ?

**Comment by chuwy** [comment]
@miike in docstring we have

```scala
  * @param data reference to Schema
  * @param schema attached data instance itself
```

While it should be:

```scala
  * @param schema reference to Schema
  * @param data attached data instance itself
```

**Comment by miike** [comment]
Simple - I've added a PR for the change.
