### ISSUE TITLE
Add support to igluctl for temporary access key

### ISSUE THREAD

**Issue by jrluis** [snowplow/iglu#395]
When running a setup with cross account role access there is no option to use temporary access key.

To use the temporary access key we need to pass the access key id, secret access key and also the **session token**. 

Tried to run igluctl using the following options:
- Passing access key id, secret access key and session token using env vars
- Creating a profile with access key id, secret access key and session token

None of the above options worked. There is no way to directly pass the session token to igluctl.

The aws documentation on temporary access key is at https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html#using-temp-creds-sdk-cli

**Comment by alexanderdean** [comment]
@jrluis - please don't link to internal Snowplow documentation from public repos

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/18
