### ISSUE TITLE
Server: add possibility to mark schemas as draft

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#403]
At this stage schema is saved in DB, but not versioned and not available via `/schemas/` endpoint. Instead available only on `/drafts/` endpoints

/cc @ninjabear @lhache

**Comment by alexanderdean** [comment]
I like this idea. What is the rationale for not associating a draft against a version - we are saying there can only be one unwritten draft per schema?

**Comment by chuwy** [comment]
> we are saying there can only be one unpublished draft per schema?

No, I think having multiple drafts should be very useful.

Our reasoning here was following:

1. Server should disallow wrong versions for final schemas (e.g. ADDITION where it should be REVISION) - but draft doesn't have to follow this protocol.
2. Somebody can publish this version out of sync
3. Its better to leave the version decision to the Server, not to human
4. If we'll define drafts by version `/draft/com.acme/event/1-0-1` then we also cannot have multiple drafts for version. Therefore it would be easier to define them as simple natural numbers: `/draft/com.acme/event/1` (`2`,`3`,`4`...)

**Comment by alexanderdean** [comment]
Sounds good, thanks for clarifying

**Comment by alexanderdean** [comment]
Can we add this into R10?

**Comment by oguzhanunlu** [comment]
Sure we can add, but couple of points to clarify.

1) We'll need to add new fields like `isDraft` and `draftNo` to `schemas` table. I guess @chuwy refers to existing iglu servers' migration to new version.

2) Will we offer `/draft/` version of each `/api/schemas/` endpoint? If so, will only difference be allowance to upload/get without version?

**Comment by ninjabear** [comment]
We use [flyway](https://flywaydb.org/) for database migrations, YMMV
