### ISSUE TITLE
Server: add Schema DDL as validation backend

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#406]
Right now we're using only FGE Json Schema validator to check schemas, but it lacks whole set of Igluctl linters

/cc @lhache @ninjabear

**Comment by alexanderdean** [comment]
How big a job is this @chuwy ? This is high priority for taking this to customers.

**Comment by chuwy** [comment]
It depends on how closely we need to follow FGE's validation report format. Just adding checks won't be any kind of big job, but it will lack things like line numbers, pointer-format will be different and other things that can be minor.
