### ISSUE TITLE
igluctl: send data application/json content-type

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#422]
Right now `static push` uses form-encoded data. We need to come up with deprecation plan and remove it entirely https://github.com/snowplow/iglu/issues/421

E.g,

1. igluctl 0.6.0 and Server =0.5.0 (R11): check Server version, use `application/json`
2. igluctl 0.6.0 and Server <0.5.0: check Server version, use form-encoded data, print deprecation message
3. igluctl 0.7.0 and Server <0.5.0: fail with meaningful message ("probably you're using outdated Server?")

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/15
