### ISSUE TITLE
Schema DDL: add linter for fields that will have identical name after normalization

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#430]
We have a case where user defined two columns: `column_name` and `columnName`. They both are getting transformed into `column_name` and BigQuery mutator fails to add this column. Same problem can happen for Redshift.

Related: https://github.com/snowplow/iglu/issues/343

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/14
