### ISSUE TITLE
igluctl: Feature request to read schema names from Iglu repo

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/iglu#435]
There are a number of ways that uploading schemas can go awry, which can cause issues in taking new tracking live. One common one is in accidentally uploading to the wrong location in Iglu (eg. uploading to the wrong location (think `root/schemas/schemas`). 

It's tricky to debug these as they're usually accidents which haven't been noticed, and are usually discovered via some kind of 'schema not found' error in bad rows. 

If igluctl was able to print a list of schemas in the repos (with their full paths), the UX would improve a lot, by:
- Improving the schema upload workflow (after uploading a schema, check that everything is expected before taking tracking changes live)
- Offering a fast and easy way to debug bad rows which simply offer a 'schema not found' error

I'm guessing this is achievable and not a security risk (since anyone using it would also have creds to write to Iglu), but not sure if it fits well into the roadmap. :)

**Comment by colmsnowplow** [comment]
I share your thoughts there Anton - what I'm thinking here is less that this is the solution to a given issue, but that it makes the process of uploading and debugging more user friendly by offering a means to confidently confirm that the schema has been uploaded as expected. 

You're right about the solution to the above issue (and I think there's an issue open about this problem specifically elsewhere) - let's think of the 'list schemas' functionality more as a 'better UX' feature than a solution to a specific problem. 

It offers users more confidence in carrying this task out (which I think is an important component of the user experience here), and it's also a more robust way to debug problems than checking the GitHub repo for schemas (since it's possible to have a schema in Iglu that's not on GH).

**Comment by chuwy** [comment]
I understand, @colmsnowplow. My point was the it is impossible to achieve, unfortunately. 

On the other hand, I also understand the problem of wrong paths and good news is that it will be solved once we start to migrate to Iglu Server. It is impossible to upload to wrong path with Iglu Server, it is a problem of static registry specfically.

**Comment by alexanderdean** [comment]
> On the other hand, we do not offer any API to list static registry.

The only way of doing this would be by statically generating listings and inserting them into the hierarchy as actual files. I think it's just too complicated.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/14
