### ISSUE TITLE
Scala Core: fix repeated .. in canonical iglu regex

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#443]
Placeholder ticket to test: https://github.com/snowplow/iglu/blob/master/0-common/scala-core/src/main/scala/com.snowplowanalytics.iglu/core/SchemaKey.scala#L52-L56

**Comment by chuwy** [comment]
Indeed, it passes the validation. Thanks @mhadam. I need someone more experienced with regexes to fix it however, leaving until next release.

**Comment by mhadam** [comment]
This is what I came up with for global contexts:
https://github.com/snowplow/snowplow-javascript-tracker/blob/issue/405/core/lib/contexts.ts#L61

but that's for validating "schema rules", I think this will validate vendors correctly for you:
`((?:[a-zA-Z0-9-_]+\.)+(?:[a-zA-Z0-9-_]+))`

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-scala-core/issues/20
