### ISSUE TITLE
update roadmap doc

### ISSUE THREAD

**Issue by techieshark** [snowplow/iglu#444]
The wiki's [roadmap](https://github.com/snowplow/iglu/wiki/Product-roadmap) has an outdated "current release":

> The current release of Iglu is 0.3.0.

The current version appears to be nearly 0.5 (or 0.6?). 

Seems like an interesting project! I'm curious what the updated roadmap might look like.

Thanks.

**Comment by chuwy** [comment]
Thanks @techieshark! It is a shame we abandoned the Roadmap page. I'll flesh it out ASAP.

**Comment by chuwy** [comment]
Done!
