### ISSUE TITLE
Schema DDL: support anyOf property

### ISSUE THREAD

**Issue by mhadam** [snowplow/iglu#445]
It seems like this property is missing. igluctl is giving me `Optional field doesn't allow null type` with optional properties in schemas that are defined like this for example: `"anyOf": [{"type": "string"}, {"type": "null"}]`.

**Comment by chuwy** [comment]
Yep, `anyOf` is tricky as well as [`oneOf`](https://github.com/snowplow/iglu/issues/250). But I agree we should support them.

In order to implement union type in JSON Schema however you can use `"type": ["string", "null"]`

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/13
