### ISSUE TITLE
Schema DDL: add derivator module

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#463]
Derivator is a distant relative of [Schema Guru](https://github.com/snowplow/schema-guru/), which also can derive a common schema out of multiple schemas.

We need this module to properly support [oneOf](https://github.com/snowplow/iglu/issues/250), [anyOf](https://github.com/snowplow/iglu/issues/445), tuple array schemas etc in target databases. All these properties need to derive a common schema to be mapped into a single column.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/12
