### ISSUE TITLE
Igluctl: anomalous error on lint

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/iglu#478]
Lint returns this error:

```
Directory [/[my-Dir]./schemas] contains schemas of [com.acme/some_event] which has gaps between schema versions. Migrations can be inconsistent.
```

But I don't think there are actually gaps between versions. The following versions are present for the schema in question:

`1-0-0`, `1-0-1`, `2-0-0`, `2-0-1`, `2-0-2`, `2-0-3`, `2-0-4`, `2-0-5`, `2-0-6`, `2-0-7`, `2-0-8`, `2-0-9`,  `2-0-10`

Suspect it's either to do with the jump from 1-0-1 to 2-0-0 or the double-digit in `2-0-10`.

**Comment by chuwy** [comment]
Which version of igluctl did you try, @colmsnowplow? Also, can you make sure all of them are consistent in filename and self-describing metadata?

**Comment by colmsnowplow** [comment]
> Which version of igluctl did you try, @colmsnowplow?

Was running 0.4.0, same result after bumping to 0.5.0. (I think that's the latest?)

> Also, can you make sure all of them are consistent in filename and self-describing metadata?

Yup. Above comment is output of an `ls` and have just manually checked the metadata which looks the same for all 10.

**Comment by chuwy** [comment]
Here's the actual logic https://github.com/snowplow/iglu/blob/master/0-common/igluctl/src/main/scala/com.snowplowanalytics.iglu/ctl/Common.scala#L109-L126

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/11
