### ISSUE TITLE
Sendgrid webhook issue iglu files

### ISSUE THREAD

**Issue by StephenHonor** [snowplow/iglu#491]
Hello,

I was unsure where to post this. However, effectively sendgrid webhook events are being declined because the iglu file states the sg_event_id is between 22 and 48 characters.

However, sendgrid state this can be up to 100 characters.

https://sendgrid.com/docs/for-developers/tracking-events/event/#json-objects

Kind regards,
Stephen

**Comment by BenFradet** [comment]
hey @StephenHonor , can you post this issue in https://github.com/snowplow/iglu-central ? cc @dilyand
