### ISSUE TITLE
Error while reading json files - it works on one linux instance and fails on others

### ISSUE THREAD

**Issue by TalyGin** [snowplow/iglu#497]
`00:15:18  File [/home/jenkins/agent/workspace/OneSpot/RC/OneSpot-Snowplow-Schemas/onespot-snowplow-schemas/schemas/com.onespot/onsite-unit/jsonschema/1-0-5] fetching and parsing failed: [Input length = 1]
00:15:18  File [/home/jenkins/agent/workspace/OneSpot/RC/OneSpot-Snowplow-Schemas/onespot-snowplow-schemas/schemas/com.onespot/onsite-unit/jsonschema/1-0-4] fetching and parsing failed: [Input length = 1]
00:15:18  File [/home/jenkins/agent/workspace/OneSpot/RC/OneSpot-Snowplow-Schemas/onespot-snowplow-schemas/schemas/com.onespot/onsite-unit/jsonschema/1-0-3] fetching and parsing failed: [Input length = 1]
00:15:18  File [/home/jenkins/agent/workspace/OneSpot/RC/OneSpot-Snowplow-Schemas/onespot-snowplow-schemas/schemas/com.onespot/onsite-unit/jsonschema/1-0-2] fetching and parsing failed: [Input length = 1]
00:15:18  File [/home/jenkins/agent/workspace/OneSpot/RC/OneSpot-Snowplow-Schemas/onespot-snowplow-schemas/schemas/com.onespot/onsite-unit/jsonschema/1-0-1] fetching and parsing failed: [Input length = 1]`

These files exist, generation works fine on my local machine. But it fails on CI server, I tried several slaves, ubuntu, centos based - and it fails. What I may need to check?

**Comment by chuwy** [comment]
Hey @TalyGin, sorry missed this message (we're deprecating the monorepo in favor of dedicated repos, so don't pay much attention). I'm assuming you're talking about igluctl? Which version did you use?

**Comment by chuwy** [comment]
Closing the ticket, but please, feel free to raise on https://discourse.snowplowanalytics.com/ or dedicated repo.
