### ISSUE TITLE
Igluctl - add lint handling of array w/unspecified element types

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/iglu#498]
Specifying a field as `array` without specifying the type of elements will pass igluctl lint with no warnings or errors. 

However, having this will lead to problems at load stage for at least one storage target (BigQuery). Best to add at least a warning for this case I think.

**Comment by chuwy** [comment]
Thanks, Colm. Moved to https://github.com/snowplow-incubator/schema-ddl/issues/49
