### ISSUE TITLE
QUESTION: how  self-describe json relates to json-schemas?

### ISSUE THREAD

**Issue by tatitati** [snowplow/iglu#503]
Sorry for the question, I know that iglu-client is trying to add JSON Schema Draft v7 support (https://github.com/snowplow/iglu/issues/303), however in iglu-client i can read that it "Only support Self-describe json." This bring me some questions:

- I'm wondering how different are both, I see that there is an attempt for self-descriptive-json to support features from json-schemas, so what gives self-describe-json that doesn't give json-schemas?
- Is self-describe-json superseeding json-schema or adding new features like a wrapper?
- why not using json-schema which seems to be the standard?

Sorry for the bunch of questions, is something I couldn't read in the doc so far. 

Thanks a lot

**Comment by chuwy** [comment]
Hey @tatitati! Thanks for your interest!

First, I'd like to address some confusion (which I also had when first stumbled upon Iglu). There are two tightly coupled, but totally opposite kinds of entities:

1. Self-describing JSONs ([example](https://github.com/snowplow-incubator/snowplow-postgres-loader/blob/release/0.1.0/config/config.json)). Plain payload that claim that it is valid against some JSON Schema (using `schema` keyword, not `$schema`).
2. Self-describing JSON Schemas ([example](https://github.com/snowplow-incubator/snowplow-postgres-loader/blob/release/0.1.0/src/main/resources/iglu-client-embedded/schemas/com.snowplowanalytics.snowplow.storage/postgresql_config/jsonschema/3-0-0)). Plain _JSON Schema_ that has attached meta-data (using `self` keyword).

These two kinds of entities are tightly coupled and meant to be used together. From `schema` key in _JSON_ you know what _schema_ you need to use to validate (and do more cool stuff) it. So data always refer to schema.

So to actually address your questions:

> Is self-describe-json superseeding json-schema or adding new features like a wrapper?

Self-describing JSONs do neither, but Self-describing _shcmeas_ do latter

> why not using json-schema which seems to be the standard?

We are using it, complying all standards ([see meta-schema](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0))

**Comment by tatitati** [comment]
Thanks a lot @chuwy  for the great answer, it was really helpful.
Also I will close the question, I have all the information I need.


Thanks!
