### ISSUE TITLE
Make it possible to overwrite an existing schema

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#73]
This may be possible already - needs testing.

**Comment by fblundun** [comment]
This is already what happens when you upload a schema with the same identifier as an existing schema.

**Comment by fblundun** [comment]
Update: you have to use PUT, not POST, to overwrite. If you POST you get

```
{
  "status" : 401,
  "message" : "This schema already exists"
}
```

**Comment by alexanderdean** [comment]
That sounds good and RESTful...
