### ISSUE TITLE
Server: allow super user to upload schemas

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu#83]
At the moment a user with the "write" permission can upload schemas but a user with the "super" cannot. Is this intentional?

https://github.com/snowplow/iglu/blob/d8afbb6fd0c145aa1ae7c8bca07b2412391e30f5/2-repositories/scala-repo-server/src/main/scala/com.snowplowanalytics.iglu.server/model/Schema.scala#L544

**Comment by BenFradet** [comment]
Yes, it was a design choice: the super user was only meant to create other api keys.

However, I agree that it is rather arbitrary, feel free to change it.

**Comment by alexanderdean** [comment]
This is very painful today, because even if you are superuser, you have to use different keys to upload different vendors of schemas.
