### ISSUE TITLE
Server: only add metadata to schema JSON if ?metadata=1

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu#86]
At the moment a request for a schema with metadata returns this:

``` json
{
  "$schema" : "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
  "description" : "Schema for an ad click event",
  "self" : {
    "vendor" : "com.snowplowanalytics.snowplow",
    "name" : "ad_click",
    "format" : "jsonschema",
    "version" : "1-0-0"
  },
  "type" : "object",
  "properties" : {
    "clickId" : {
      "type" : "string"
    },
    "impressionId" : {
      "type" : "string"
    },
    "zoneId" : {
      "type" : "string"
    },
    "bannerId" : {
      "type" : "string"
    },
    "campaignId" : {
      "type" : "string"
    },
    "advertiserId" : {
      "type" : "string"
    },
    "targetUrl" : {
      "type" : "string",
      "minLength" : 1
    },
    "costModel" : {
      "enum" : [ "cpa", "cpc", "cpm" ]
    },
    "cost" : {
      "type" : "number",
      "minimum" : 0
    }
  },
  "required" : [ "targetUrl" ],
  "dependencies" : {
    "cost" : [ "costModel" ]
  },
  "additionalProperties" : false,
  "metadata" : {
    "location" : "/api/schemas/com.snowplowanalytics.snowplow/ad_click/jsonschema/1-0-0",
    "createdAt" : "11/12/2015 13:16:19",
    "updatedAt" : "11/12/2015 13:16:19",
    "permissions" : {
      "read" : "private",
      "write" : "none"
    }
  }
}
```

instead of something like this:

``` json
{
  "value": {
    "$schema" : "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
    "description" : "Schema for an ad click event",
    "self" : {
      "vendor" : "com.snowplowanalytics.snowplow",
      "name" : "ad_click",
      "format" : "jsonschema",
      "version" : "1-0-0"
    },
    "type" : "object",
    "properties" : {
      "clickId" : {
        "type" : "string"
      },
      "impressionId" : {
        "type" : "string"
      },
      "zoneId" : {
        "type" : "string"
      },
      "bannerId" : {
        "type" : "string"
      },
      "campaignId" : {
        "type" : "string"
      },
      "advertiserId" : {
        "type" : "string"
      },
      "targetUrl" : {
        "type" : "string",
        "minLength" : 1
      },
      "costModel" : {
        "enum" : [ "cpa", "cpc", "cpm" ]
      },
      "cost" : {
        "type" : "number",
        "minimum" : 0
      }
    },
    "required" : [ "targetUrl" ],
    "dependencies" : {
      "cost" : [ "costModel" ]
    },
    "additionalProperties" : false,
  },
  "metadata" : {
    "location" : "/api/schemas/com.snowplowanalytics.snowplow/ad_click/jsonschema/1-0-0",
    "createdAt" : "11/12/2015 13:16:19",
    "updatedAt" : "11/12/2015 13:16:19",
    "permissions" : {
      "read" : "private",
      "write" : "none"
    }
  }
}
```

**Comment by alexanderdean** [comment]
Good catch!

**Comment by alexanderdean** [comment]
Actually - this wasn't a bug. The reason was that we didn't want to break inter-op with static Iglu server and existing Iglu clients by changing the location of the JSON Schema in the response from the `$` (root) to `$.value`.

**Comment by fblundun** [comment]
My reason for wanting to avoid this is that it will cause problems if anybody ever decides to add their own metadata to their schema. Also, when the repo supports non-JSON documents (e.g. Redshift DDLs) it won't be possible to add the metadata in this way - we would need different formats for the metadata response depending on the document type.

Maybe the metadata should be something which can generalise to any sort of data, e.g.

```
{
  "metadata": {...},
  "value": "{\"fields\": {...}}"
}
```

Then to extract the value from the metadata envelope you parse the string `$.value` using the appropriate parser for the expected type of that field.

**Comment by alexanderdean** [comment]
I agree @fblundun - embedding metadata etc inside schemas is unsustainable. We need an overall response envelope which works for a) different schema types (JSON, Avro, Redshift, Postgres, Thrift, Protocol Buffers) and b) for non-schema types e.g. migrations and mappings.

We should treat the current static repo behavior as v1 of the Iglu schema API, and what we will work on is v2. We should have a ghost release to land this v2 behavior, and we will need to introduce new Iglu clients to support v2 too (lucky we are doing this before too many Iglu clients have proliferated).

**Comment by alexanderdean** [comment]
Updated the ticket so that the metadata capability is not lost, but it is backgrounded, given a) it's not often used and b) it is rather unusually structured.
