### ISSUE TITLE
Scala Repo Server: ensure that createdat and updatedat are the same when a schema is first uploaded

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu#92]
Generate one timestamp and use it twice rather than generating a new timestamp for each field.

**Comment by BenFradet** [comment]
This is implemented in the feature/scala-repo-server-0.2.0

**Comment by fblundun** [comment]
Thanks Ben - I actually only noticed this because I was looking at that branch!

**Comment by BenFradet** [comment]
No problem, I just thought I'd let you know.
