### ISSUE TITLE
Scala Repo Server: change header name from api_key to apikey so it survives ELB

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu#94]

**Comment by fblundun** [comment]
See http://stackoverflow.com/questions/28553110/aws-elb-custom-headers-nginx for background

**Comment by fblundun** [comment]
This must have been caused by the [underscores_in_headers setting](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers).

**Comment by alexanderdean** [comment]
Ah! Interesting
