### ISSUE TITLE
Add deployment script

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu#97]
I can't think of a simpler way than this:

We would have a script to deploy the app. The script would require AWS credentials. It would deploy the app, providing a randomly generated master username and password for the associated RDS database.

We would then poll the output of describe-db-instances until we find an instance whose username matches the one we created the database with. We would get the security group associated with this instance, change it to allow access from the user's IP, use psql to insert a randomly generated super API key (which would also be shown to the user), and finally change the security group back.

**Comment by alexanderdean** [comment]
This sounds good - I guess let's write this in Python so we can use Boto...

**Comment by fblundun** [comment]
I'm having a problem with doing this using the CLI instead of the console. More details: http://stackoverflow.com/questions/34175278/configuring-elastic-beanstalk-to-create-an-rds-database-using-ebextensions-file

**Comment by alexanderdean** [comment]
Hey @fblundun - what the advantages are of co-creating the RDS instance with the Beanstalk cluster, rather than just creating both resources independently and wiring them together?

**Comment by fblundun** [comment]
The main advantage is that if they are created simultaneously, the beanstalk application gets informed of the information it needs to access the database via environment variables. This apparently doesn't happen if they are created separately - see http://serverfault.com/a/578023

**Comment by alexanderdean** [comment]
Closing this ticket in favour of a step-based setup guide!

**Comment by fblundun** [comment]
The setup guide is now available [here](https://github.com/snowplow/iglu/wiki/Setting-up-Iglu-on-Elastic-Beanstalk)
